### ISSUE TITLE
这个j是怎么来的，该如何去掉？

### ISSUE THREAD

**Issue by shnode** [wklken/k-vim#100]
![image](https://cloud.githubusercontent.com/assets/7784713/7151031/e608862e-e356-11e4-8173-a97b7ea8bc49.png)

**Comment by wklken** [comment]
你是说`j`?

在某个位置 `ma` 之后你到了文件其他位置想快速会到标记位置, `'a`

去掉文件所有标记 `m<space>`

具体见[文档](https://github.com/wklken/k-vim#mark%E8%B7%B3%E8%BD%AC-kshenoyvim-signature)
根据自己需求决定是否去除

================

**Comment by shnode** [comment]
好吧，功能实在太强，误触发造成的这个j，非常感谢。
