### ISSUE TITLE
终端不能正常显示问题

### ISSUE THREAD

**Issue by wangshunping** [wklken/k-vim#104]
使用GUI能够正常显示，如图：
![image](https://cloud.githubusercontent.com/assets/10842398/7448050/fae51356-f241-11e4-9ebb-8381c791fbba.png)

但是在终端直接显示(mvim -v） 不能正常显示配色：
![image](https://cloud.githubusercontent.com/assets/10842398/7448054/173e0134-f242-11e4-9ffa-5227771a0249.png)

有人现在遇到这样的情况吗？

**Comment by ruanyl** [comment]
用terminal的话，应该设置let g:solarized_termcolors=16， 并且为你的iterm2安装solarized的preset：https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized

**Comment by wangshunping** [comment]
多谢指教。
我没有用iterm2, 用的是原生的终端。我在vimrc 中加了你提到的这句 let g:solarized_termcolors=16,没有效果

**Comment by ruanyl** [comment]
这里有原生的支持，你可以试试。https://github.com/altercation/solarized/tree/master/osx-terminal.app-colors-solarized

**Comment by wangshunping** [comment]
多谢帮助，已解决。

我在这个页面上（ http://ethanschoonover.com/solarized/vim-colors-solarized）找到了这样的一句：。
If you do use the custom terminal colors, solarized.vim should work out of the box for you. If you are using a terminal emulator that supports 256 colors and don’t want to use the custom Solarized terminal colors, you will need to use the degraded 256 colorscheme. To do so, simply add the following line before the colorschem solarized line:

let g:solarized_termcolors=256
Again, I recommend just changing your terminal colors to Solarized values either manually or via one of the many terminal schemes available for import.

大意是要把let g:solarized_termcolors=256 放在主题设置之前，然后就解决了，多谢帮助。

**Comment by ruanyl** [comment]
你设置之后颜色显示是和solarized一样的不？

2015-05-11 13:11 GMT+03:00 wangshunping <notifications@github.com>:

**Comment by wangshunping** [comment]
应该是一样的吧～
上图：
![image](https://cloud.githubusercontent.com/assets/10842398/7562936/333fa71a-f80b-11e4-8c31-51c059c4b7cb.png)

**Comment by ruanyl** [comment]
![01daa4d4-6ee0-4e50-bcca-5b212d5d3a9e](https://cloud.githubusercontent.com/assets/486382/7563005/ebf400b4-f7e1-11e4-9a5b-5d88b28327f9.png)

这是我iterm2的显示，我在terminal.app下跟你一样的结果。但是感觉配色也能接受，哈哈。

**Comment by fangwentong** [comment]
明显背景不一样，可以更改一下`terminal.app`的颜色配置

[这里](https://github.com/altercation/solarized/tree/master/osx-terminal.app-colors-solarized)有配置文件

**Comment by wklken** [comment]
@ruanyl 的图目测才是iterm2配合k-vim配置后的效果.....系统默认终端没搞过:(
@fangwentong  能贴下你那四行配置不? 图不方便

**Comment by fangwentong** [comment]
![image](https://cloud.githubusercontent.com/assets/5756771/7570964/e4dc21e8-f846-11e4-90da-c19a3ddc43bb.png)


上面是`terminal.app`打开的效果,  可以添加一个 `Solarized Dark` 的描述文件， 并设为默认值， 具体描述文件可以到 [这里](https://github.com/altercation/solarized/tree/master/osx-terminal.app-colors-solarized) 下载.

![image](https://cloud.githubusercontent.com/assets/5756771/7571022/5480fc94-f847-11e4-877d-6e04b2bed413.png)

**Comment by ruanyl** [comment]
@fangwentong 谢谢，terminal.app已经显示正常

**Comment by wangshunping** [comment]
@fangwentong  果然可以了，多谢。
虽然下一个文件然后import 进去显得逼格好低(゜▽＾*))

**Comment by wklken** [comment]
已加入README.md

谢谢大家:)
