### ISSUE TITLE
YouCompleteMe可以配置成全自动补全吗？

### ISSUE THREAD

**Issue by swkhack** [wklken/k-vim#106]
我把YCM配置好后写python代码。YCM补全总要按<c-Space>后才能出现，比如在导入模块时需要按<c-Space>后才能补全实际安装的模块名，或者在写c代码补全函数式也要按<c-Space>才能补全。有没有办法让它全自动补全？

**Comment by wklken** [comment]
默认`.`然后输入两个字符开始补全(印象中是YCM的配置, 可改)
如果要提前触发, 需要按键

------------

**Comment by swkhack** [comment]
那是否有办法在不输入 . 的时候就开始补全？ 即在不输入 . 的 情况下 ， 输入两个字符后开始补全？

**Comment by wklken** [comment]
可以配置输入`.`, 或者c/c++`->`, 语言关键字符, 可配置输入这些关键字符后即刻补全
但是目测是做不到输入字符就补全......

具体见YCM的文档
