### ISSUE TITLE
install.sh报错

### ISSUE THREAD

**Issue by qsnow6** [wklken/k-vim#107]
新装的vim-gnome，干净无插件的。

一键安装后缺少好多插件，clone成功无错误提示。

我的安装步骤是
1.clone
2.# ubuntu
sudo apt-get install ctags
sudo apt-get install build-essential cmake python-dev  #编译YCM自动补全插件依赖
sudo apt-get install silversearcher-ag
3.sh -x install.sh

然后就报错了，提示找不到插件

是什么原因，那么插件要一个个手动装吗？

![2015-05-22 22 42 57](https://cloud.githubusercontent.com/assets/4144227/7773408/db96b768-00d6-11e5-9950-39eb73639aae.png)

**Comment by spacewander** [comment]
具体报错信息是？
试一下`ls ~/.vim/bundle/`，看看安装了多少个插件了？

**Comment by qsnow6** [comment]
hookman@hookman:~$ ls ~/.vim/bundle
vundle

**Comment by wklken** [comment]
到图上这步, 按Enter, 会进入插件安装界面, 继续执行等待插件逐一安装完成

没装上插件的原因应该是安装一半没耐心取消掉了.....(国内github较慢, 特别是下YCM的时候, 要有足够的耐心)

**Comment by qsnow6** [comment]
谢谢,确实是没有下完就关了.
安装完后执行./install.sh --clang-completer 编译 ,打开VIM就出下面的提示.
编译大概不到十秒就完成了.
![2015-05-23 15 38 12](https://cloud.githubusercontent.com/assets/4144227/7782961/defccc5e-0161-11e5-80b6-4260ef578ffa.png)


还有这个,是下载插件的时候提示的错误,是这个问题造成的吗
![2015-05-23 15 31 42](https://cloud.githubusercontent.com/assets/4144227/7782959/cb903aca-0161-11e5-9803-b89611ac8af0.png)

**Comment by LittleKey** [comment]
```
CMake Error at ycm/CMakeLists.txt:62 (message):
  No pre-built Clang 3.6 binaries for 32 bit linux.  You'll have to compile
  Clang 3.6 from source.  See the YCM docs for details on how to use a
  user-compiled libclang.
```
他的意思是让你自己去编译YCM。。。或者换一个64位的linux？或者关掉YCM

**Comment by qsnow6** [comment]
确实是没有32bit linux的二进制包，试着去下载clang 3.6来编译，结果都编译不过去，我可以提个建议，如果时间 允许的话，可以出个clang 32bit的编译教程吗

**Comment by e788b1** [comment]
Building YouCompleteMe on Vim 7.4 in Ubuntu Trusty (32 bit)

Posted on March 6, 2015
<http://modal.us/blog/2015/03/06/youcompleteme-on-vim-7-4-in-ubuntu-trusty-32-bit/>
 by erat <http://modal.us/blog/author/erat/>

http://modal.us/blog/2015/03/06/youcompleteme-on-vim-7-4-in-ubuntu-trusty-32-bit/

Oh, how I love documentation for open source software. In some cases it’ll
get you close, or at least close enough to take things the remaining 2% of
the way to completion. However, far too often it barely gets you off the
ground.

YouCompleteMe is a great code-completion bundle for Vim. When it’s
installed and configured and running it’s so amazing that you’ll question
many of the reasons you use an IDE for development.

That said, getting the damn thing installed on a 32 bit version of Ubuntu
“Trusty” will make you want to climb a tower with a high-power rifle.

What absolutely slays me about this is that the steps to get through the
installation should not be mysterious, especially when the folks that
respond to “why isn’t this installing” questions indignantly point users to
the docs. Some of us actually read installation docs, but if the
installation docs do not document our installation issues, we have to find
answers elsewhere. Still, “read the docs” is the mantra, and it’s not
helpful.

*The problem*

If you’re installing YouCompleteMe on a 32 bit installation of Ubuntu
“Trusty” (14.04), you’re going to hit a roadblock when you run the
following command from within* ~/.vim/bundle/YouCompleteMe*:

./install.sh --clang-complete

Specifically, you’re going to be told that there is no 32 bit version of
*clang* 3.6, then you’re going to be told to read the docs about building
it. Don’t bother looking for answers for this in the docs. It’ll just make
you mad.

Here’s what you need to do:

*Add the LLVM PPAs to apt*

Go to LLVM’s apt page <http://llvm.org/apt/> and scroll down until you get
to the Ubuntu section. You will see a number of lines starting with “deb”
and there will be no instructions about what to do with them. Re-read my
opening rant about documentation for open source software, then return here.

These are “PPAs.” They need to be added to your *apt* configuration. As of
today, here are the lines you need to be concerned with (for Ubuntu
“Trusty”):

deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main
deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty main
# 3.5
deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.5 main
deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.5 main
# 3.6
deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main
deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main

You need to add these lines to the end of your */etc/apt/sources.list* file.
Any text editor will do the trick (yes, *sudo* will be required).

Once that’s done, run the following command:

sudo apt-get update

That will update your *apt* system to recognize the files in the PPAs you
just added.

*Install the “qualification branch” of LLVM*

Back at the LLVM apt <http://llvm.org/apt/> page, scroll until you get to
the section titled “Install (qualification branch).” Copy/paste the first
*wget* command to retrieve the archive signature (if you haven’t *sudo*‘d,
you may find yourself looking at an empty line in your terminal and no
command prompt. If this happens, it’s *sudo*waiting for your password),
then copy/paste the last command that installs all of the LLVM packages.
You’ll have to precede this last command with *sudo*. Why was that omitted?
Who knows.

I guess you could do the installation piecemeal by running the second
command that only installs *clang*and *lldb* and then just add the packages
you want, but unless you have disk space constraints it’s probably best to
just get all of it. I know for a fact that *libclang* will be needed in
addition to *clang*, so go from there.

*Run the YCM installation with the system libclang*

Yeah, the install docs stress that you should not do this. I’m not sure
why. Maybe YCM thinks everyone’s system *libclang* is one that shipped with
the Linux distro. Don’t know, doesn’t matter. You want to use the one you
just installed.

Change to your* ~/.vim/bundle/YouCompleteMe* directory and run the
following command:

./install.sh --clang-complete --system-libclang

You should see everything build.

Good luck.
*tips: no 64bit， no ycm.*

2015-06-04 1:12 GMT+08:00 qsnow6 <notifications@github.com>:

**Comment by wklken** [comment]
YCM/Clang/Vim编译等, 都有第三方具体文档

通过对应项目可以找到, `k-vim`不会提供具体安装教程, 涉及到翻译/更新/同步的问题, 不现实

但是尽量会在文档中提示入口

--------------
YCM 很强大, 唯一的缺点就是不好装
