### ISSUE TITLE
大牛能不能施舍一个windows版的install？

### ISSUE THREAD

**Issue by zhjawe** [wklken/k-vim#109]

**Comment by wklken** [comment]
sorry, 暂不考虑支持

不过我看有用gvim配合k-vim的, 可以看下gvim如何配置, 只需要核心文件迁移过去应该就行, 当然, YCM什么的似乎会比较困难:(

**Comment by rexdf** [comment]
实际上Windows上面跑得很好，YCM也是可以用的，只是要在Cygwin下面跑。关键在于，不要自己编译llvm和clang，用官方自带的。

另外，虽然我没有试过，但是msys2应该可以。它的vim和llvm、clang滚动更新，系统更新非常频繁。

**Comment by rexdf** [comment]
只是启动太慢，基本上我不太用。

主要用Sublime Text 3，另外YCM也是支持Windows版本Sublime的，需要自己写一个通信协议，而且搜索的头文件，需要借用cygwin的gcc头文件，但是不能用cygwin的llvm/clang，需要用mingw自己编译。

**Comment by wklken** [comment]
我的建议是不折腾
条件允许的话切到ubuntu或者osx(虚拟机也行)

或者, 找台机器配置好, 然后在windows下使用secureCRT或者putty登陆上去开发

**Comment by rexdf** [comment]
cygwin上面倒是不需要折腾，`sh -x install.sh`倒是可以一步成功的。

不过也是呢，都用Windows了，那里还需要用vim，基本可以认为不在需求范围呢。

**Comment by rexdf** [comment]
http://blog.rexdf.org/2015/06/%E5%9C%A8visual-studio%E7%BC%96%E8%AF%91gvim%E5%92%8Cycmd/

**Comment by hexinchao** [comment]
强烈建议在基本配置里面加上
au BufEnter *.py,*.c,*.cpp,*.h,*.java silent! setlocal colorcolumn=80
这个可以画出80个字符宽的竖线，规范代码的宽。

bundle插件加上 tag生成  taglist功能

" Auto generate tags & scope files, for python, install pycsope==0.3
"   $ sudo pip install pycscope==0.3
" KEYS:
"   <F4> (re)Generate tags&cscope.out
"   <F3> Add addtional ctags file
if executable('cscope') && executable('ctags') && executable('md5sum')
    Bundle 'basilgor/vim-autotags'
    let g:autotags_ctags_opts="--python-kinds=-iv --c++-kinds=+px --fields=+ialS
            \ --extra=+q"
    let g:autotags_cscope_file_extensions=".py .cpp .cc .cxx .m .hpp .hh .h .hxx
            \ .c .idl .java"
    au BufEnter *.py let g:autotags_no_global=1 | if executable('pycscope.py') |
            \ let g:autotags_cscope_exe="pycscope.py -i cscope.files -- " | endif
    au BufLeave *.py let g:autotags_cscope_exe="cscope"
endif

undle 'Tagbar'
nnoremap <leader>tb :TagbarToggle<CR>
let g:tagbar_width=30
au filetype python,java,c,cpp silent! nested :TagbarOpen
