### ISSUE TITLE
无法显示buffer列表

### ISSUE THREAD

**Issue by Anniywell** [wklken/k-vim#110]
README：
ctrl+<space> 得到当前tab的buffer列表
我的ctrl+space已被输入法占用，我修改如下：
let g:ctrlspace_default_mapping_key="<C-q>"
依然不显示list

**Comment by wklken** [comment]
查看 ctrl-space的文档
https://github.com/szw/vim-ctrlspace#gctrlspace_set_default_mapping

关注这两个配置项

另g:ctrlspace_default_mapping_key 需要给定一组有效的键位

**Comment by Anniywell** [comment]
不好意思，上午let g:ctrlspace_default_mapping_key=""没有打全，已经是有效键位了
另外把输入法的ctrl+space替换掉，C+Space也无法显示buffer list

**Comment by wklken** [comment]
目测是ctrlspace 的锅.....使用文档中说明的方法无效

可以使用命令行模式调用, 举例绑定 <leader>a

```
nnoremap <silent> <Leader>a :CtrlSpace<CR>
```

**Comment by Anniywell** [comment]
恩，用nnoremap好用；
另外如何让bufferlist一直显示在vim上方

**Comment by wklken** [comment]
查看minibuffer....or google
