### ISSUE TITLE
请问有什么组件可以让下面这段代码按照pep8规范排列？

### ISSUE THREAD

**Issue by rogerdehe** [wklken/k-vim#112]
代码如下

        stu = Student(id=id
                          name=name,
                          year=year,
                          batch=batch,
                          location=location,
                          score=score)

vim在按回车以后缩进并不合理，请问有没有让python代码按照pep8自动格式化的插件？

**Comment by wklken** [comment]
使用 https://github.com/google/yapf 这个项目, 可以直接格式化

但是目前不支持中文, 提了个尚未合并 https://github.com/google/yapf/pull/145

可以临时使用切出来的分支: https://github.com/wklken/yapf

vimrc.bundle中配置快捷键:

```
autocmd FileType python nnoremap <leader>y :0,$!yapf<Cr>
```

------------------------------
如果发现类似的工具或者插件可以发出来大家一起试用:)

**Comment by j5shi** [comment]
https://github.com/tell-k/vim-autopep8.git

**Comment by liuhao2050** [comment]
So, 怎么配置可以 让不符合pep8的位置被 高亮，多余空格被高亮？
