### ISSUE TITLE
youcompleteme补全不齐？

### ISSUE THREAD

**Issue by qsnow6** [wklken/k-vim#113]
折腾了个把礼拜终于把youcompleteme装上了，但是在使用中发现，补全机制并不是很完善。
在python中，连re模块居然都不能智能补全，不知道你们是不是这样的。

![2015-06-05 02 40 47](https://cloud.githubusercontent.com/assets/4144227/7991712/d5b94cba-0b2c-11e5-9d1b-1896fc0eaece.png)

**Comment by wklken** [comment]
正常安装后的效果应该是......

![image](https://cloud.githubusercontent.com/assets/2002216/7997678/7229623e-0b63-11e5-9faa-4e86352e8b10.png)

**Comment by wklken** [comment]
正常来说, 支持任意import包的补全

注意 `vimrc.bundles`中, 目前使用的conf是ycm自带的
```
if !empty(glob("~/.vim/bundle/YouCompleteMe/cpp/ycm/.ycm_extra_conf.py"))
    let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/YouCompleteMe/cpp/ycm/.ycm_extra_conf.py"
endif
" new version
if !empty(glob("~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"))
    let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"
endif
```

**Comment by qsnow6** [comment]
配置跟你发的是一样的，生效的应该是new version下的设置，conf路径是放在`~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py`下的。
我有的是k-vim默认的配置，没经过修改，还有哪些影响补全的参数


![2015-06-05 20 41 14](https://cloud.githubusercontent.com/assets/4144227/8006111/4f05e9d4-0bc3-11e5-8d0f-912e5854d29c.png)

**Comment by qsnow6** [comment]
解决了，居然换一个目录就可以了。。。

**Comment by wklken** [comment]
@qsnow6 换了什么目录?

**Comment by qsnow6** [comment]
真不好意思说，当前目录下有一个re.py，冲突了。

**Comment by wklken** [comment]
同issues: https://github.com/wklken/k-vim/issues/60
......

**Comment by qsnow6** [comment]
:'( 真不好意思说，当前目录下有 一个re.py，被覆盖了
