### ISSUE TITLE
文件管理器的切换

### ISSUE THREAD

**Issue by qsnow6** [wklken/k-vim#117]
在正常模式下按,n打开文件管理器，选择好文件后，按o打开。然后想再切换回文件管理器要按哪个键？

我现在是重新再开关一次文件管理器，也就是按两次,n来切换，感觉好麻烦。

**Comment by wklken** [comment]
两个方法:

1. `ctrl + h` 跳转到左侧

2. 设置 nerdtree 打开的时候自动关闭
