### ISSUE TITLE
改了下主题后，再使用时提示：函数名必须以大写字母开头或者包含冒号: togglefold()，修改成大写后正常。

### ISSUE THREAD

**Issue by kenchichen** [wklken/k-vim#118]
第  179 行:
E128: 函数名必须以大写字母开头或者包含冒号: togglefold()
第  187 行:
E193: :endfunction 不在函数内
第  219 行:
E128: 函数名必须以大写字母开头或者包含冒号: numbertoggle()
第  225 行:
E193: :endfunction 不在函数内
第  313 行:
E128: 函数名必须以大写字母开头或者包含冒号: hidenumber()
nonumber
第  322 行:
E193: :endfunction 不在函数内

根据提示把这些函数的首字母改成大写就可以了，不知道是什么问题。

**Comment by wklken** [comment]
`k-vim`的vimrc中都是大写的
https://github.com/wklken/k-vim/blob/master/vimrc#L178

你的配置文件首字母为什么是小写的呢?

**Comment by kenchichen** [comment]
谢谢关注！不太清楚为啥是小写的，之间执行过好几个其他的操作，也重复安装了几次，没有详细记录过程～

**Comment by wklken** [comment]
可以拉取最新的, diff下

问题关闭
