### ISSUE TITLE
关于语法高亮

### ISSUE THREAD

**Issue by shenxs** [wklken/k-vim#119]
语法高亮当有两个不同类型的文件打开的时候，比如一开始我打开了一个markdown文件，然后又打开一个cpp的文件两个文件分屏显示的时候cpp文件的语法高亮就变成了markdown的语法高亮了

**Comment by wklken** [comment]
https://github.com/wklken/k-vim/issues/151

已经解决了 , 下个版本更新, 你可以先自己手动改下
