### ISSUE TITLE
int main(int argc, char** argv) 处报错

### ISSUE THREAD

**Issue by lijingjiang** [wklken/k-vim#120]
你好！你的vim配置非常好用尤其是youcompleteme 插件，但是他始终会在int main(int argc, char** argv) 处报错提示unused parameter argc。不知道怎样配置才能让其不提示这个错误信息。

**Comment by wklken** [comment]
syntastic语法检查插件提示的错误, 定义了参数但是在函数体内没有使用, 跟YCM无关

至于如何关闭某类语言的语法检查, google或者查看其项目主页

https://github.com/scrooloose/syntastic
