### ISSUE TITLE
ycm 如何用tab选中候选条目

### ISSUE THREAD

**Issue by chy373** [wklken/k-vim#125]
现在tab在insert模式下时往后4个空格，然后候选条目没了

**Comment by j5shi** [comment]
If you use `neocomplete`:

```
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<BS>"
    inoremap <expr><BS> pumvisible() ? "<ESC>:call neocomplete#close_popup()<CR>a<BS>" : "<BS>"
```

**Comment by wklken** [comment]
目前选取候选使用 `ctrl-n` / `ctrl-p` 或者  `ctrl-j`/`ctl-k`
这份配置改写了tab, 作为snippets的补全

鱼和熊掌不可兼得, 可以看下配置中YCM相关映射, 自行定义

**Comment by gooker** [comment]
ctrl-n / ctrl-p 或者 ctrl-j/ctl-k 有问题.

需要编辑.vimrc.bundle 内将snippets对应的都删了,,,如果你不用.
将youcompleteme的 <up> 和<down> 分别修改未<tab>和<s-tab>
