### ISSUE TITLE
在非插入模式下上下左右键无法移动光标？

### ISSUE THREAD

**Issue by kigkrazy** [wklken/k-vim#126]
在非插入模式下上下左右键无法移动光标？

**Comment by LittleKey** [comment]
是的，禁用掉了  强行用hjkl吧

**Comment by wklken** [comment]
https://github.com/wklken/k-vim#自定义快捷键

**Comment by Zhang21** [comment]
我按照README注释之后，上下可用，左右不可用，显示`:bn`, `:bp`。

```
    6 " 主要按键重定义                                                                  
    5                                                                                       
    4 " 关闭方向键, 强迫自己用 hjkl                                                 
    3 " map <Left> <Nop>                                                    
    2 " map <Right> <Nop>     
    1 " map <Up> <Nop>
  333 " map <Down> <Nop> 
```

是我注释错误吗？

**Comment by omaidb** [comment]
天哪,原来是这样,变成hjkl了

**Comment by zewenhs** [comment]
> 我按照README注释之后，上下可用，左右不可用，显示`:bn`, `:bp`。
> 
> ```
>     6 " 主要按键重定义                                                                  
>     5                                                                                       
>     4 " 关闭方向键, 强迫自己用 hjkl                                                 
>     3 " map <Left> <Nop>                                                    
>     2 " map <Right> <Nop>     
>     1 " map <Up> <Nop>
>   333 " map <Down> <Nop> 
> ```
> 
> 是我注释错误吗？

把这两句也注释掉
![2021-09-22_14-33](https://user-images.githubusercontent.com/7780577/134294132-c3acefb5-d361-43c0-af82-927138579179.png)
