### ISSUE TITLE
关于粘贴时代码缩进格式错乱

### ISSUE THREAD

**Issue by wklken** [wklken/k-vim#127]
当我们复制整段代码想粘贴进去的时候, 格式会错乱

以前的处理方式`:set paste`, 或者按`F5`(k-vim绑定的动作)

找到了一个解决方式

https://coderwall.com/p/if9mda/automatically-set-paste-mode-in-vim-when-pasting-in-insert-mode

已测试并使用, 可以更新下, 如果发现问题, 麻烦反馈下

**Comment by ilaipi** [comment]
```
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"
```

不知道为啥你的配置里把这两行去掉了

我这里必须加上这两行才能自动切换

**Comment by wklken** [comment]
这两配置是切光标外观的




Sent from Mail Master
On 01/14/2016 17:31, 杨亚梦 wrote:
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"


不知道为啥你的配置里把这两行去掉了

我这里必须加上这两行才能自动切换

**Comment by ilaipi** [comment]
```
" F5 set paste问题已解决, 粘贴代码前不需要按F5了
" F5 粘贴模式paste_mode开关,用于有格式的代码粘贴
" Automatically set paste mode in Vim when pasting in insert mode
function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
```

您好，这段在`tmux`下怎么改改呢？
