### ISSUE TITLE
source k-vim/vimrc 报错

### ISSUE THREAD

**Issue by bfwg** [wklken/k-vim#129]
运行没有任何问题 每次source vimrc就会有这种错误：
<img width="673" alt="screen shot 2015-08-19 at 9 15 09 pm" src="https://cloud.githubusercontent.com/assets/12819525/9375588/6518ada4-46b7-11e5-885a-7ee9a69bcd57.png">
我在用mac

**Comment by wklken** [comment]
vimrc不是shell脚本，当然不能source, vim启动时会自动加载





Sent from Mail Master
On 08/20/2015 12:15, bfwg wrote:

运行没有任何问题 每次source vimrc就会有这种错误：

我在用mac

**Comment by bfwg** [comment]
@wklken 啊 我以为跟bashrc 一样。
所以不需要关心他的报错。
大爱 谢谢你
