### ISSUE TITLE
macvim 打开go代码错误

### ISSUE THREAD

**Issue by gatspy** [wklken/k-vim#130]
在macvim中打开go代码出现下面错误
Error detected while processing function go#package#FromPath..go#package#Paths:
line   14:
E121: Undefined variable: goroot
E116: Invalid arguments for function len(goroot) != 0 && isdirectory(goroot)
E15: Invalid expression: len(goroot) != 0 && isdirectory(goroot)
E121: Undefined variable: goroot
E116: Invalid arguments for function len(goroot) != 0 && isdirectory(goroot)
E15: Invalid expression: len(goroot) != 0 && isdirectory(goroot)
Press ENTER or type command to continue   

--------------------------------------------------------------------------
go version
go version go1.4.2 darwin/amd64  

--------------------------------------------------------------------------
go env 信息
GOARCH="amd64"
GOBIN="/Users/MAC/App/go/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/MAC/work/golang"
GORACE=""
GOROOT="/Users/MAC/App/go"
GOTOOLDIR="/Users/MAC/App/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"   

-------------------------------------------------------------------------
which gocode
/Users/MAC/App/go/bin/gocode
which gotags
/Users/MAC/App/go/bin/gotags
把vim-gocode插件注销就不保错，是不是因为vim-gocode不支持go 1.4，还是其他原因呢？
ken有打算把此插件更新到vim-go吗?vim-gocode已经很久没有更新了。

**Comment by wklken** [comment]
看报错信息应该是goroot的问题

我这边使用的golang是通过brew安装的
并且在.zshrc中声明了
```
export GOROOT=/usr/local/go
export GOPATH=/Users/ken/goworkspace
export PATH=$PATH:$GOROOT/bin:/Users/ken/goworkspace/bin/


~ » echo $GOROOT                                                                                                                                                                           ken@Luna-mac
/usr/local/go
```
具体报错的文件在
`.vim/bundle/vim-gocode/autoload/go/package.vim`, 定义goroot变量失败
可以确认下运行时变量是否ok

-----------------------------------------------------

平时使用golang频率不是很高, 所以暂时gocode/gotags够用, 之前试用过`vim-go`, 但是感觉太重了, 更偏向于轻量一些的插件.

不过你也可以自己安装使用下, 如果觉得ok, 将插件配置及使用提pr :)
