### ISSUE TITLE
Macvim 用命令退出 `:q` YCM进程不会被停止

### ISSUE THREAD

**Issue by bfwg** [wklken/k-vim#132]
这个问题可能是Macvim的bug， YCM按道理会在接收到VimLeave以后被停止 但是除非在mac上直接用`Command ＋ q` 退出 Macvim 否则其他任何退法 包括(`:q, :wq, :bd...`) 都会导致 YCM进程不被停止 就好像 VimLeave 永远不会被叫。
![image](https://cloud.githubusercontent.com/assets/12819525/9433820/6909c38e-49ec-11e5-94bc-46e42dc1ec87.png)
我用的是Vim 7.4 如上图 我已经设置了 最后一个tab被关闭会 杀掉macvim进程， 进程确实被杀了
但是由于VimLeave没被叫 每次运行一次 vim 就会遗留一个YCM 进程 如图
![image](https://cloud.githubusercontent.com/assets/12819525/9433823/6dc0a5be-49ec-11e5-88d3-63741fde8858.png)
![image](https://cloud.githubusercontent.com/assets/12819525/9433825/7127ac34-49ec-11e5-8c45-221e5f8f5273.png)

最后补充一下 在iterm 或者原生 terminal 都不会出现这种问题 但是 我发现 在gui 的 vim 上就会出这种问题 除去macvim 我有在Ubuntu上装 gvim 也是同样的问题 一定要点叉子关或者 快捷键关 不然用`:q`这样管就会遗留进程。

YCM进程 3小时Idel就会自动杀掉 但是 相信我 3小时也能开很多个 而且我经常不关机 受够了老用 killall 杀哪些Python 进程

求帮助

**Comment by LittleKey** [comment]
试试[这个](http://vimdoc.sourceforge.net/htmldoc/eval.html#v:dying)，大概可以治标不治本的解决问题。。

**Comment by bfwg** [comment]
@LittleKey  加这行`:au VimLeave * if v:dying | echo "\nAAAAaaaarrrggghhhh!!!\n" | endif`在`.vimrc`吗？

**Comment by LittleKey** [comment]
可以确定一下是否有回调VimLeave吧。。然后还能看下dying的值有没有问题。。
如果没有回调的话可以看看 [VimLeavePre](http://vimdoc.sourceforge.net/htmldoc/autocmd.html#VimLeavePre) 有没有回调。。有的话就像上面那样手写来关掉ycmd之类的

不是什么好的解决问题的方法。。

**Comment by bfwg** [comment]
@LittleKey 
木有任何反应 是不是没救了？

**Comment by LittleKey** [comment]
VimLeave和ViewLeavePre都没有吗？

**Comment by LittleKey** [comment]
试试`au VimLeave * echo "call on VimLeave"`
退出的时候应该会在终端上print那个`call on VimLeave`

(如果你gui上不会显示stdout的话，你可以换其他能确定有调用的命令试一试
比如`au VimLeave * !killall ycmd`之类的

**Comment by bfwg** [comment]
@LittleKey 
经过一些测试， gvim 或者 mvim离开时都不会call Vimleave 所以目前这个问题也无法解决。
我还有个问题， 最近在写一些jsx react的东西， 怎么把scrooloose/syntastic里面加入对jsx的监测？

**Comment by LittleKey** [comment]
VimLeave没有, VimLeavePre也没有吗？
其他问题另开issue吧

**Comment by bfwg** [comment]
@LittleKey 
没有喔 除了打开可以call VimEnter 只要是离开都不会回调任何离开函数。

**Comment by LittleKey** [comment]
这样的话我也没有办法了。。。刚看完Charlotte#11 心好痛。。。

**Comment by wklken** [comment]
.........我也再追>_<#
@LittleKey

**Comment by linkeyeasy** [comment]
YCM 我的一直无法启动，所以没有这个问题咯:joy:

**Comment by wklken** [comment]
@linkeyeasy  还是配置下好, 实在不行看文档手工上. 搞完了, 编码效率提升非常多

**Comment by linkeyeasy** [comment]
已配置，有提示的时代又回来了 
------------------ Original ------------------
