### ISSUE TITLE
mvim自动打开NERDtree的问题

### ISSUE THREAD

**Issue by Geng-G-Razor** [wklken/k-vim#133]
我的mac安装k-vim之后，mvim会自动打开NERDtree，vim不会。
注释掉.vimrc.bundles的402行

        Bundle 'scrooloose/nerdtree'
问题解决，原因不明

**Comment by wklken** [comment]
这个插件文档中有相关配置项说明么？


Sent from Mail Master
On 08/25/2015 19:23, Geng-G-Razor wrote:

我的mac安装k-vim之后，mvim会自动打开NERDtree，vim不会。
注释掉402行

    Bundle 'scrooloose/nerdtree'


问题解决，原因不明

**Comment by Geng-G-Razor** [comment]
![screen shot 2015-08-25 at 19 28 23](https://cloud.githubusercontent.com/assets/10413931/9465476/7de24870-4b5f-11e5-8034-61a8c3e3a96f.png)
有，但是默认是禁用的。

**Comment by wklken** [comment]
分别注掉nerdtree和nerdtreetabstoggle试试看
如果不行, 查阅下对应文档写入显式关闭的配置

**Comment by wklken** [comment]
https://github.com/wklken/k-vim/issues/165
