### ISSUE TITLE
python补全不正确

### ISSUE THREAD

**Issue by Finalcheat** [wklken/k-vim#135]
import别的模块的补全不正确，比如下面：

a.py

```
#!/usr/bin/env python
# encoding: utf-8

import datetime
def getD():
    return datetime.datetime.now()
```

b.py
<img width="532" alt="qq20150830-1 2x" src="https://cloud.githubusercontent.com/assets/4862842/9566864/3cd9aa2e-4f49-11e5-81dc-c9c812e31b2d.png">

请问这是youcompleteme的问题吗？连这个都不能正常的补全吗？

**Comment by wklken** [comment]
能明确下哪个地方不正确么? 指的是什么?

**Comment by Finalcheat** [comment]
d是datetime.datetime，d再减去datetime.datetime得到的t是datetime.timedelta，但是列出的关于t的补全全部都是datetime.datetime的方法，应该补全的是datetime.timedelta方法才对啊。

**Comment by LittleKey** [comment]
确实有这个bug。。。我这也是。。。

2015-08-30 22:05 GMT+08:00 Finalcheat <notifications@github.com>:

>
> d是datetime.datetime，d再减去datetime.datetime得到的t是datetime.timedelta，但是列出的关于t的补全全部都是datetime.datetime的方法，应该补全的是datetime.timedelta方法才对啊。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wklken/k-vim/issues/135#issuecomment-136141121>.
>



-- 
这里是上条当麻保护协会

**Comment by spacewander** [comment]
可以考虑去Jedi补全引擎报下bug，ycm就是用这个引擎给补全Python代码的。

**Comment by wklken** [comment]
好像暂时无解.......

**Comment by wklken** [comment]
无解
