### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hexinchao** [wklken/k-vim#136]
强烈建议在基本配置里面加上
au BufEnter .py,.c,.cpp,.h,*.java silent! setlocal colorcolumn=80
这个可以画出80个字符宽的竖线，规范代码的宽。

bundle插件加上 tag生成 taglist功能

" Auto generate tags & scope files, for python, install pycsope==0.3
" $ sudo pip install pycscope==0.3
" KEYS:
" (re)Generate tags&cscope.out
" Add addtional ctags file
if executable('cscope') && executable('ctags') && executable('md5sum')
Bundle 'basilgor/vim-autotags'
let g:autotags_ctags_opts="--python-kinds=-iv --c++-kinds=+px --fields=+ialS
\ --extra=+q"
let g:autotags_cscope_file_extensions=".py .cpp .cc .cxx .m .hpp .hh .h .hxx
\ .c .idl .java"
au BufEnter *.py let g:autotags_no_global=1 | if executable('pycscope.py') |
\ let g:autotags_cscope_exe="pycscope.py -i cscope.files -- " | endif
au BufLeave *.py let g:autotags_cscope_exe="cscope"
endif

undle 'Tagbar'
nnoremap tb :TagbarToggle
let g:tagbar_width=30
au filetype python,java,c,cpp silent! nested :TagbarOpen

**Comment by wklken** [comment]
额, 这个看个人风格吧.....每天用27寸大屏我已经很少遵从80个字符的原则了, 囧
另外, taglist在某一版本从k-vim中移除了
原因是, tagbar更友好, 配合其他插件已经够了, taglist如果喜欢个人也可以装上
I really don't like it......
