### ISSUE TITLE
fedora下很多依赖没有

### ISSUE THREAD

**Issue by Ka-chanNi** [wklken/k-vim#137]
YCM的依赖，还有silverserver在fedora下都找不到，有人知道是什么吗？

**Comment by wklken** [comment]
YCM 和silverserver, 没有在fedora的安装实践过, 因为我虚拟机没有这个>_<(只有ubuntu和centos)
但是根据文档应该可以正常装上吧
如果有同学有实践可以发上来哈, 或者pr README.md发过来
