### ISSUE TITLE
安装结束后打开vim会出现YouCompleteMe unavailable: requires Vim compiled with Python 2.x supportUltiSnips requires py >= 2.7 or py3

### ISSUE THREAD

**Issue by solitudechn** [wklken/k-vim#139]
我的系统是debian unstable 不知道是不是系统原因，网上找到的解决方法是 安装 vim-nox 安装完成后解决问题

（如果我说错了不要骂我啊^_^）

**Comment by wklken** [comment]
编译vim, 带上python支持就好了

https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source
