### ISSUE TITLE
minibuffer解除封印后，上端还是不显示多buffer

### ISSUE THREAD

**Issue by londbell** [wklken/k-vim#141]

**Comment by wklken** [comment]
sorry, 基本已经不维护minibuffer, 不过我刚才解开注释, 然后`BundleInstall`, 是生效的
你是不是解开注释没有进行安装?
现在用ctrl-space替代, 感觉更符合直觉, 可以试试哈

**Comment by londbell** [comment]
oops,谢谢，我现在正常了= =，不过ctrl-space我不太会用，而且minibuffer上面有tab比较直观，我是小白= =

**Comment by wklken** [comment]
:) 可以看看文档, 其实就是ctrl+空格, 然后选择就能切换
