### ISSUE TITLE
去除json文件引号自动隐藏

### ISSUE THREAD

**Issue by kongkongyzt** [wklken/k-vim#143]
在编辑json文件的时候,遇到引号的地方会自动隐藏,如下:

>vim下的显示

![vim](https://cloud.githubusercontent.com/assets/5072174/10127180/507048e8-65d0-11e5-9288-d167c8c12a10.png)

>sublime下的显示

![sublime](https://cloud.githubusercontent.com/assets/5072174/10127185/5be5b974-65d0-11e5-9d0d-e1354ee603eb.png)

***实际上大多数时候隐藏引号给我造成了很多困扰,请问一下在哪里可以把这个功能关闭?***

**Comment by wklken** [comment]
正常k-vim安装完后, 不会有这个问题哦(自动隐藏这种一般插件不会提供这类功能)
你是不是另外装了一些插件? 建议用二分法定位下是哪个插件造成的

**Comment by kongkongyzt** [comment]
解决了,是我的问题,谢谢

**Comment by skywalkerlee** [comment]
@stormeyes 您好，我也遇到了这个问题，请问您是怎么解决的

**Comment by stormeyes** [comment]
@skywalkerlee 有一个插件冲突了, 年代久远忘了是哪个插件了, 用二分法定位一下即可

**Comment by zaggerj** [comment]
@skywalkerlee 请问是什么原因造成的啊？我现在也这样了，遇到显示json的时候，就自动隐藏引号，很奇怪的显示方式。

**Comment by skywalkerlee** [comment]
是一个json的插件造成的，时间太久忘记是哪个了，停用几个插件试一下吧

zaggerj <notifications@github.com> 于2019年8月5日周一 下午2:55写道：

**Comment by zaggerj** [comment]
@skywalkerlee 好的，谢谢

**Comment by idea1110** [comment]
可以试试这个配置：`let g:vim_json_conceal=0` ，配置到 .vimrc 或 init.vim中

**Comment by SKHUO** [comment]
一般来说，会是indentLine或者vim-json这两个插件造成的
