### ISSUE TITLE
vim-ctrlspace 默认快捷键设置变量名已更改

### ISSUE THREAD

**Issue by denglj** [wklken/k-vim#146]
新版ctrlspace设置：
`let g:CtrlSpaceDefaultMappingKey = "<C-Space>"`

而不是
`let g:ctrlspace_default_mapping_key = "<C-Space>"`

**Comment by wklken** [comment]
多谢提醒, 不过k-vim配置中并没有修改ctrlspace的配置

**Comment by ilaipi** [comment]
我想问下，这个插件怎么用？
我有个需求：假如我有好几个文件的好几个地方都有一行代码，现在我要把这行改一下。
我在第一个地方改好了，然后删掉不要的那行。把改好的新行`yy`复制，然后到第二个地方，先`p`，然后需要`dd`掉原来的那行。然后我到第三个地方的时候，再`p`怎么能贴出来我最终要改的结果？

我现在必须在`dd`后再次`yy`，感觉这样有点笨。

这个插件所谓的管理`buffer`，是管`dd`、`yy`之类的命令存东西的地方吗？

**Comment by petrewoo** [comment]
@ilaipi 
1. 你可以使用copy paste.
2. 这个插件管理的buffer是指你打开的文件buffer.跟yy、dd之类的不是一个地方，但是我不知道yy、dd的存储机制。

如果有新的线索我也会提供。

**Comment by ilaipi** [comment]
@petrewoo 谢谢回复

**Comment by ilaipi** [comment]
@petrewoo  `<leader>y`我经常用，不过这个快捷键需要先选中，对这个场景来说还是`dd`，`yy`来的更快
