### ISSUE TITLE
如何控制默认加载项

### ISSUE THREAD

**Issue by kingedit** [wklken/k-vim#147]
比如我不想加载一些插件，我如何去配置这些文件。谢谢了

**Comment by LittleKey** [comment]
参考 [README.md](https://github.com/wklken/k-vim/blob/master/README.md) -> 安装步骤 -> 安装/卸载/更新插件 -> 删除插件

**Comment by kingedit** [comment]
然而我是想在开始安装的时候就控制加载的项目，实现定制化

**Comment by kingedit** [comment]
你好，我已经找到了，在
vimrc.bundles
配置文件中
