### ISSUE TITLE
怎么取消normal模式下回车选中当前项？还有insert模式下，`<`输入响应慢，找了很久都找不到修改的地方。

### ISSUE THREAD

**Issue by thestylelove** [wklken/k-vim#150]

**Comment by spacewander** [comment]
修改回车选中当前项：
请注释掉 https://github.com/wklken/k-vim/blob/master/vimrc#L269

`<`输入响应慢：
应该是有什么映射是以`<`开头了，所以需要等下一步的输入。
使用`:map`看看？

**Comment by thestylelove** [comment]
@spacewander  不是的，你说的那个是popup menu里面的选中，我指的是normal下的选中，等于normal下的`viw`。

**Comment by wklken** [comment]
@thestylelove 

注掉`vimrc.bundles` line 48附近的 `Plug 'docunext/closetag.vim'`, 这个插件导致的

这个插件会自动补全html/xml标签, 但是不分场合开启的.......应该可以配置只在某些类型文件才生效

**Comment by wklken** [comment]
改成

```
Plug 'docunext/closetag.vim', { 'for': ['html', 'xml'] }
```

下一版本更新
