### ISSUE TITLE
version 9.1 TODO List

### ISSUE THREAD

**Issue by wklken** [wklken/k-vim#153]
打算年前再花一两天测试和处理下, 发9.1版本

计划变更的地方:
1. README.md, 重写, 配新的演示图及说明, english version可能来不及>_<
2. vimrc/vimrc.bundles, 重新梳理, 感觉有点乱了
3. bundle -> plugin, 使用plugin关键字
4. 剪贴板增强
5. shell交互
7. ?

---------------

短期主要还是关注可能存在的 bug或者现有功能不符合直觉的地方
希望大家多多提意见和建议, 有一些自己添加的改键/改进/新插件等等, 欢迎推荐

目前除了k-vim, 还维护了 [vim-for-server](https://github.com/wklken/vim-for-server), 以及 [k-tmux](https://github.com/wklken/k-tmux), 目前都是我主要的工具, 各种痛点目前也就基于自己使用中遇到的进行改进, 更想看看大家使用过程中有些什么不爽, 不舒服的点, 一起寻找解决方法, 更高效地去码代码, 有更多时间去干别的事情:)

**Comment by ruanyl** [comment]
:+1:  重新梳理vimrc/vimrc.bundles的想法，我们不谋而合。我这里做了一个初步的梳理：[vimrc.bundles](https://github.com/ruanyl/bigvim/blob/master/vimrc.bundles) 基本上是参考了 [junegunn](https://github.com/junegunn) 的结构。希望尽快看到你的版本！

**Comment by zbing3** [comment]
shell交互 正需要

**Comment by wklken** [comment]
@ruanyl  感谢, 新的版本参考了你的配置:)

9.1版本基本已经梳理完了, 基本上全部重写了, 打算将readme拆分掉, wiki中写faq以及插件使用, readme中只保留一些最基本的东西

剩余要做的
1.重写readme, 增加wiki等
2.改写vimrc/vimrc.bundles中的注释
3.细节修改, 目前细节部分的处理, 包括一些键位修改还没有测试完
4.剪贴板增强及shell交互增强, 还在试用插件.....不一定会在这个版本做了

争取月底前发....本来今天想发的, 奈何文档还没写, 注释还没改....>_<

以下是当前这个版本的changelog, 还会再增加一些东西, 有什么问题和意见希望提哈

-------------------


version: 9.1 大版本更新

```
插件部分:
1. 使用 'junegunn/vim-plug' 替代 'VundleVim/Vundle.vim' 来管理插件, 安装/更新速度更快
2. 支持自定义插件集合, 可以配置自己需要安装的插件
3. 去除tomorrow主题插件 'chriskempson/vim-tomorrow-theme'
4. Javascript插件, 使用 'othree/javascript-libraries-syntax.vim' 替代 'nono/jquery.vim',
5. Javascript插件, 使用 'othree/yajs.vim' 替代 'jelera/vim-javascript-syntax'
6. 去除 minibufferexpl 所有配置(ctrlspace替代)
7. 去除 taglist 所有配置(tagbar和ctrl-funky替代)
8. Python插件, 增加 'hynek/vim-python-pep8-indent'
9. Python插件, 去除 'kevinw/pyflakes-vim'
10. Go插件, 使用 'fatih/vim-go' 替代 'Blackrush/vim-gocode'
11. 快速移动, 增加插件 'unblevable/quick-scope', 按f/F/t/T时触发, 行内快速移动, 与 easymotion 互补
12. (bundle_groups配置了tmux)tmux插件 'christoomey/vim-tmux-navigator'
13. (bundle_groups配置了json)json插件 'elzr/vim-json'

细节:
1. 增加 leader+w 保存文件
2. YCM 开启语法关键字补全 'let g:ycm_seed_identifiers_with_syntax=1'
3. 插件 'terryma/vim-expand-region', 增加自定义每次加减的区域配置
4. 解决在insert mode粘贴代码缩进错乱问题(以前需要:set paste . 即k-vim中F5快捷键, 现在不需要了)
```

**Comment by wklken** [comment]
已发布, 文档细节待完善, 关闭
