### ISSUE TITLE
Error detected while processing Syntax Auto commands for "*":

### ISSUE THREAD

**Issue by zky001** [wklken/k-vim#156]
E492: Not an editor command: RainbowParenthesesLoadBraces

**Comment by wklken** [comment]
info:
1. 是否安装完插件了, 即 `ll ~/.vim/bundle/rainbow_parentheses.vim/`目录存在 (应该是这个原因)
2. vim 版本

**Comment by zky001** [comment]
1.ll ~/.vim/bundle/rainbow_parentheses.vim/不能找到这个目录
2.vi版本7.3
3.我试着改了k－vim的vimrc.bundles的bundle＃rc()为bundle#begin()还是这个错误
4.将其中的vimrc.bundles 所有的bundle换为plugin还是不行

**Comment by spacewander** [comment]
试下运行`BundleUpdate`，重新安装下？搞不好是网络问题。

**Comment by zky001** [comment]
还是不行，网络绝对ok,diu bao 少

**Comment by wklken** [comment]
.........
插件没装上, 重装

```
:BundleInstall
```
