### ISSUE TITLE
跳转到模块或函数定义处

### ISSUE THREAD

**Issue by kaito-kidd** [wklken/k-vim#159]
有没有比较好的插件，可以在方法调用处，直接跳到方法体里面？
这个功能应该很常用吧，例如使用tornado时可以跳到tornado某个模块或方法里？
再或者跳到本项目中其他类的方法中？

**Comment by wklken** [comment]
文档中有写
[YCM](https://github.com/wklken/k-vim#代码自动补全-valloricyoucompleteme)

```
,jd  跳转到函数定义, 分屏打开一个buffer(非常有用!!!!!!!!!)
,gd  跳到声明位置, 仅 filetypes: c, cpp, objc, objcpp, python 有效(比较少用)
```

**Comment by kaito-kidd** [comment]
我看到这个了，但是本文件内的，可以跳过去，但是别的模块或者第三方的，就跳不进去。
提示RuntimeError: Can't jump to definition or declaration.

**Comment by wklken** [comment]
,jd/,gd都试过?
标准库源文件,第三方库等等, 只要import都可以跳过去的

这个是YCM带的, 前提是确定ycm安装成功, 且确认以下文件存在

```
      " old version
      if !empty(glob("~/.vim/bundle/YouCompleteMe/cpp/ycm/.ycm_extra_conf.py"))
          let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/YouCompleteMe/cpp/ycm/.ycm_extra_conf.py"
      endif
      " new version
      if !empty(glob("~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"))
          let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"
      endif
```

具体可以去看YCM文档
================

**Comment by kaito-kidd** [comment]
这2个快捷键我都试过，都是只能跳到本文件的方法或定义。
其他模块的就提示RuntimeError: Can't jump to definition or declaration.错误。
我刚才确认了，新版本的~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py确实是存在的。

**Comment by kaito-kidd** [comment]
我编译按照好YouCompleteMe之后，拷贝了你的配置：
```
" ################### 自动补全 ###################

" 代码自动补全
"迄今为止用到的最好的自动VIM自动补全插件
"重启 :YcmRestartServer
Bundle 'Valloric/YouCompleteMe'
"youcompleteme  默认tab  s-tab 和自动补全冲突
"let g:ycm_key_list_select_completion=['<c-n>']
let g:ycm_key_list_select_completion = ['<Down>']
"let g:ycm_key_list_previous_completion=['<c-p>']
let g:ycm_key_list_previous_completion = ['<Up>']
let g:ycm_complete_in_comments = 1  "在注释输入中也能补全
let g:ycm_complete_in_strings = 1   "在字符串输入中也能补全
let g:ycm_use_ultisnips_completer = 1 "提示UltiSnips
let g:ycm_collect_identifiers_from_comments_and_strings = 1   "注释和字符串中的文字也会被收入补全
let g:ycm_collect_identifiers_from_tags_files = 1

"let g:ycm_seed_identifiers_with_syntax=1   "语言关键字补全, 不过python关键字都很短，所以，需要的自己打开

" 跳转到定义处, 分屏打开
let g:ycm_goto_buffer_command = 'horizontal-split'
" nnoremap <leader>jd :YcmCompleter GoToDefinition<CR>
nnoremap <leader>jd :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap <leader>gd :YcmCompleter GoToDeclaration<CR>

" 引入，可以补全系统，以及python的第三方包 针对新老版本YCM做了兼容
" old version
if !empty(glob("~/.vim/bundle/YouCompleteMe/cpp/ycm/.ycm_extra_conf.py"))
    let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/YouCompleteMe/cpp/ycm/.ycm_extra_conf.py"
endif
" new version
if !empty(glob("~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"))
    let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"
endif
```
是这样操作吧，还有其他什么需要按照的吗？

**Comment by wklken** [comment]
没有需要其他操作的了

```
from re import compile
```
然后光标在compile上, 使用快捷键试试

如果还不行, 只能自行去排查YCM 配置是否有问题了, 或者与其他插件是否有冲突(如果是k-vim带的, 都不会存在冲突)

**Comment by PangPangPangPangPang** [comment]
遇到了同样的问题
`from re import compile`
可以跳转 然而别的模块就跳不过去了

**Comment by longhai123** [comment]
@kaito-kidd 您好，请问现在问题解决了吗？

**Comment by kaito-kidd** [comment]
@longhai123 没有解决，可能和楼主其他配置不同吧，没有深究。
建议使用pycharm开发工具，很强大，你想要的功能都有。

**Comment by longhai123** [comment]
@kaito-kidd C工作者^_^

**Comment by cp542524698** [comment]
@kaito-kidd  问题解决了麽，我在c++工程下，没法跳转；
RuntimeError: Can't jump to definition.
log：
142 2017-06-14 18:08:11,518 - INFO - Received command request
143 Traceback (most recent call last):
144   File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 861, in _handle
145     return route.call(**args)
146   File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
147     rv = callback(*a, **ka)
148   File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 109, in wrapper
149     return callback( *args, **kwargs )
150   File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
151     body = callback( *args, **kwargs )
152   File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 83, in RunCompleterCommand
153     request_data ) )
154   File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 336, in OnUserCommand
155     return command( self, request_data, arguments[ 1: ] )
156   File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 121, in <lambda>
157     self._GoToDefinition( request_data ) ),
158   File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 176, in _GoToDefinition
159     raise RuntimeError( 'Can\'t jump to definition.' )
160 RuntimeError: Can't jump to definition.

**Comment by JasonOldWoo** [comment]
YCM可能没有工程的概念吧。所有工程概念的IDE都会让你选择有哪些源文件的，否则怎么知道定义去哪个文件寻找呢？
如果有人知道YCM怎么创建工程的话麻烦告诉我下，谢了！

**Comment by lsff** [comment]
@JasonOldWoo 可以试下 bear make， 基于 make 生成项目的文件，在ycm中配置一下就可以读到工程的符号。https://github.com/rizsotto/Bear

**Comment by JasonOldWoo** [comment]
@lsff 谢谢，基于make的方法研究过了，但还是太复杂，而且不通用，所以我现在基本放弃了。

**Comment by daquexian** [comment]
@JasonOldWoo ycm can read compile_commands.json generated by CMake

**Comment by nlpjoe** [comment]
@wklken YCM可以补全，但是跳转出现这个错误是什么原因呢？ 没有新增插件

E15: Invalid expression: <q-mods>,                                      -1,                                      4,                                      4,
                              "GoToDeclaration")
E116: Invalid arguments for function <SNR>171_CompleterCommand
