### ISSUE TITLE
YoucompleteMe补全不能用tab选词

### ISSUE THREAD

**Issue by qhsong** [wklken/k-vim#160]
在vim 编辑模式下，YouComleteMe的提示不能用tab选词，只能用方向键，很不方便。。不知道这个是什么的问题呢？

**Comment by wklken** [comment]
tab键让给了 ultrsnips 代码片段补全....鱼和熊掌暂时没找到兼得的方法

```
ctrl+n/p
或者
ctrl+j/k
```

**Comment by qhsong** [comment]
这样子啊，我试试。

**Comment by liuhao2050** [comment]
我想要鱼怎么换回来？ @wklken

**Comment by wklken** [comment]
1. 改掉ultrsnips的补全键 https://github.com/wklken/k-vim/blob/master/vimrc.bundles#L394
2. 修改ycm的这几行  https://github.com/wklken/k-vim/blob/master/vimrc.bundles#L354

**Comment by liuhao2050** [comment]
THX ^_^

**Comment by JerryAllison** [comment]
总是提醒要重启YcmRestartServer，怎么解？


------------
Best Regards
Leo

2016-08-08 13:38 GMT+08:00 Brooks Liu <notifications@github.com>:

**Comment by qhsong** [comment]
重新make一下you complete me试试



Get Outlook for Android






On Mon, Aug 8, 2016 at 6:52 PM +0800, "Leo" <notifications@github.com> wrote:










总是提醒要重启YcmRestartServer，怎么解？





------------

Best Regards

Leo



2016-08-08 13:38 GMT+08:00 Brooks Liu <notifications@github.com>:

**Comment by JerryAllison** [comment]
能给个详细的步骤吗？谢谢。


------------
Best Regards
Leo

2016-08-08 19:03 GMT+08:00 qhsong <notifications@github.com>:

**Comment by wklken** [comment]
重新执行install.sh

或者 运行其中的 

```
cd ~/.vim/bundle/YouCompleteMe
git submodule update --init --recursive
python install.py --clang-completer
````

**Comment by JerryAllison** [comment]
出错了：

Your C++ compiler supports C++11, compiling in that mode.
-- Found PythonLibs:
/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
(found suitable version "2.7.12", minimum required is "2.6")
Downloading Clang 3.8.0
CMake Error at ycm/CMakeLists.txt:89 (file):
  file DOWNLOAD error: cannot create directory

'/Users/jla/.k-vim/bundle/YouCompleteMe/third_party/ycmd/cpp/../clang_archives'
  - Specify file by full path name and verify that you have directory
  creation and file write privileges.


CMake Error at ycm/CMakeLists.txt:98 (file):
  file COPY cannot find

"/Users/jla/.k-vim/bundle/YouCompleteMe/third_party/ycmd/cpp/../clang_archives/clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz".


tar: Error opening archive: Failed to open
'clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz'
CMake Error at ycm/CMakeLists.txt:145 (message):
  You have not specified which libclang to use.  You have several options:

   1. Set PATH_TO_LLVM_ROOT to a path to the root of a LLVM+Clang binary
distribution. You can download such a binary distro from llvm.org. This is
the recommended approach.
   2. Set USE_SYSTEM_LIBCLANG to ON; this makes YCM search for the system
version of libclang.
   3. Set EXTERNAL_LIBCLANG_PATH to a path to whatever
libclang.[so|dylib|dll] you wish to use.

  You HAVE to pick one option.  See the docs for more information.


-- Configuring incomplete, errors occurred!
See also
"/private/var/folders/vj/tz1gll5x7w927f1y_7bb6bdw0000gn/T/ycm_build.8idQhj/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/Users/jla/.k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py",
line 480, in <module>
    Main()
  File "/Users/jla/.k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py",
line 467, in Main
    BuildYcmdLib( args )
  File "/Users/jla/.k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py",
line 357, in BuildYcmdLib
    subprocess.check_call( [ 'cmake' ] + full_cmake_args )
  File
"/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py",
line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-G', 'Unix Makefiles',
'-DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib',
'-DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7',
'-DUSE_CLANG_COMPLETER=ON', '-DUSE_PYTHON2=ON',
'/Users/jla/.k-vim/bundle/YouCompleteMe/third_party/ycmd/cpp']' returned
non-zero exit status 1
Traceback (most recent call last):
  File "install.py", line 44, in <module>
    Main()
  File "install.py", line 33, in Main
    subprocess.check_call( [ python_binary, build_file ] + sys.argv[1:] )
  File
"/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py",
line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command
'['/usr/local/opt/python/bin/python2.7',
u'/Users/jla/.k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py',
'--clang-completer']' returned non-zero exit status 1


------------
Best Regards
Leo

2016-08-08 20:01 GMT+08:00 wklken <notifications@github.com>:

**Comment by JerryAllison** [comment]
刚刚下班又把这个弄了下，已搞定。
我把python重新安装了一遍
brew reinstall python --enable-shared
然后在执行编译YCM：
./install.py --clang-completer
但是还是出错，但是出错信息变了，说没有找到下载文件：
clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz

看样子是没有下载来，看了下估计是mac下普通用户权限的问题导致无法下载
在.k-vim/bundle/YouCompleteMe/把权限弄下：
sudo chown -R user *

再执行./install.py --clang-completer

ok，搞定。


------------
Best Regards
Leo

2016-08-09 13:04 GMT+08:00 Leo <jaryer@gmail.com>:

**Comment by JerryAllison** [comment]
[image: 内嵌图片 1]
可欣赏一下。

对了，还有个问题。我看插件库里有vim-airline这个，但是配置文件里貌似没有写进去？？


------------
Best Regards
Leo

2016-08-09 18:43 GMT+08:00 Leo <jaryer@gmail.com>:
