### ISSUE TITLE
安装不成功，vimrc.bundle第452行报错

### ISSUE THREAD

**Issue by subaochen** [wklken/k-vim#161]
说找不到expand_region#custom_text_objects

如果注释掉"快速选中”的所有功能，安装时vi会停在search unused plugins这个界面。

**Comment by wklken** [comment]
测试过mac/centos/ubuntu, 没发现这个问题

你的vim是否是7.4版本的?
另外, 这个错误是在执行install.sh的过程中报错, 还是所有插件安装完后, 打开vim报的?

另外, 单独注掉

452行附近,

```
    call expand_region#custom_text_objects({
      \ 'a]' :1,
      \ 'ab' :1,
      \ 'aB' :1,
      \ 'ii' :0,
      \ 'ai' :0,
      \ })
```

**Comment by subaochen** [comment]
我测试的环境是ubuntu 15.10（家里），vim的版本应该是高于7.4，因为手头的15.04中vim的版本是7.4

执行install.sh时报告452行出错，然后我注释掉了所有和快速选中相关的行，删除了.vim*，重新执行install.sh，结果跳出分左右两屏的vim，左边的一屏显示unused plugin，但是这个vim没法操作，无论按q还是试图打：执行指令均没有反应，只好关掉终端了事。重新打开终端后，发现.vim目录几乎安装完毕，很不好意思的是，刚才从家里走的急，没有再进行进一步的测试。

**Comment by wklken** [comment]
分两屏其实是vim-plug在并行安装插件, 有些插件可能安装不成功, 你需要仔细看下左边的列表状态
安装过程中的确是不能操作的, 但是一定要耐心等待安装完(取决于连github的网速)....之后会进入更漫长的ycm编译........

如果vim-plug安装失败了, 可以在整个流程过后, 进入vim, 使用`:PlugInstall`进行重新修正, 一般就ok了

如果关掉终端, 则某些插件没装, 打开vim读取配置的时候, 会有问题的.....

**Comment by subaochen** [comment]
重复执行install.sh没有问题吧？我的意思，我心急关掉了终端，可以重新打开终端执行install.sh，是否可以把没有安装成功的插件装上？

**Comment by wklken** [comment]
没问题, 不过之前有自己的.vimrc等文件, 安装第一次的时候会备份, 再安装第二次会被覆盖哦(install.sh)

一定要跑完全程, 全程跑完如果发现有没安装成功的插件, 可以单独`:PlugInstall`

**Comment by fdevops** [comment]
同是ubuntu15.10，vim 7.4+，也是提示这个函数没有定义，注释掉call expand_region#custom_text_objects这个调用就可以了，感觉需要在autoload/plugin.vim里面定义一下这个函数。

**Comment by subaochen** [comment]
测试了debian 8.2(jessie)，也存在同样的问题

**Comment by fdevops** [comment]
还有一个问题，编译YouCompleteme会提示找不到threads这个library，我只用过thread，没有用过threads，cmake 是3.1版本的，看样子像是cmake的bug

**Comment by Lyndonneu** [comment]
Error detected while processing Syntax Auto commands for "*":

**Comment by wklken** [comment]
@Lyndonneu  什么时候从git clone下来的?

**Comment by wklken** [comment]
```
expand_region#custom_text_objects
```

统一`PlugInstall`重新确认所有插件安装成功
另外, 不要再安装半途关闭窗口, 如果关闭了, 需要重头执行install.sh
