### ISSUE TITLE
command window 下面如何执行一条命令，<CR>不起作用了

### ISSUE THREAD

**Issue by hiveer** [wklken/k-vim#162]
默认情况下，在q:, q?, q/进入到command window之后，在任何一条命令上然后敲击<CR>会执行这条命令。但是现在<CR>不起作用了，请问如何执行command window下的命令呢？

**Comment by wklken** [comment]
line 283 注解掉试试

```
" 回车即选中当前项
inoremap <expr> <CR>       pumvisible() ? "\<C-y>" : "\<CR>"
```

**Comment by hiveer** [comment]
```
" Author:  wklken
" Version: 8.0
" Email: wklken@yeah.net
" BlogPost: http://wklken.me
" ReadMe: README.md
" Donation: http://www.wklken.me/pages/donation.html
" Last_modify: 2014-10-02
" Sections:
```
这是我用的版本信息，你给出的这个设置我没有找到，但是*回车即选中当前*依然起效

**Comment by wklken** [comment]
......这个是老版本的..新版本已经升级到了9.1

查了下8.0/9.0/9.1都是有这个配置的, 你仔细找下.......

**Comment by hiveer** [comment]
```
"离开插入模式后自动关闭预览窗口
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
"回车即选中当前项

"上下左右键的行为 会显示其他信息
inoremap <expr> <Down>     pumvisible() ? "\<C-n>" : "\<Down>"
```
估计我之前就删除了这行的，但是为什么**回车选中**还是起效呢？纳闷了，我用vim -u NONE -N 原生的模式启动，这个效果就没了。会不会是哪个插件有这个设置？

**Comment by wklken** [comment]
上二分调试大法吧.......全注掉, 一半半打开

**Comment by hiveer** [comment]
Sounds 刁，我试试

**Comment by hiveer** [comment]
@wklken 我把`~/.vimrc` backup 起来都还有，我有点搞不懂了，这是我的目录结构
```
hiveerli@~/workspace/insights (master)$ ls ~/.vim
.vim/            .viminfo         .vimrc.20150403  .vimrc.backup    .vimrc.bundles

hiveerli@~/workspace/insights (master)$ ls ~/.vim/
.git/          .gitmodules    README.md      UltiSnips/     install.sh     vimrc
.gitignore     .netrwhist     UPDATE_LOG.md  bundle/        others/        vimrc.bundles
```
你看看有什么问题呢？还有就是你自己的配置存在这个问题吗？还有就是我怎么升级到9.1呢？

**Comment by wklken** [comment]
从目录上看不出什么问题
要么移除所有配置, 写一个.vimrc, 开启 vim测试

---------------

升级的话, git pull拉到最新文件, 然后重新执行install.sh就可以了, 其中YCM下载非常大, 可能耗时长一些

**Comment by hiveer** [comment]
@wklken 谢啦，如果有进展我会更新的

**Comment by hiveer** [comment]
@wklken  更新到了最新的9.1，这个问题依然存在。用排除法最终确定了是这几行的问题
```
" install bundles
  if filereadable(expand("~/.vimrc.bundles"))
    source ~/.vimrc.bundles
  endif

" ensure ftdetect et al work by including this after the bundle stuff
filetype plugin indent on
```
这样的话那说明是某个或者某些插件导致的，这个就真无解了。

**Comment by wklken** [comment]
对.vimrc.bundles使用二分法....定位到具体插件就好了....

**Comment by hiveer** [comment]
等空了再按这个法子试试看

**Comment by hiveer** [comment]
@wklken 通过你建议的方法找到了这个插件：
> " 多光标选中编辑
   " multiplecursors
   Plug 'terryma/vim-multiple-cursors'

能有替代方案么？

**Comment by wklken** [comment]
@hiveer  暂时没有, 如果用不到可以去掉, 不过这个插件蛮好的, 你看下官方文档能否将其设置<cr>的键位改掉

**Comment by hiveer** [comment]
@wklken 确实挺有用的，经常用到它的功能。我在它那儿提了一个issue，正在跟进。
