### ISSUE TITLE
更新之后，打开GVIM 报错，无法分配颜色155与81，  求解啊== 之前没有问题

### ISSUE THREAD

**Issue by ShomyLiu** [wklken/k-vim#163]

**Comment by wklken** [comment]
截下图, 另外尝试自己调试下(注释掉, 一半一半解开), 我这边没有windows环境, k-vim发布前没在gvim中验证过>_<#

**Comment by ShomyLiu** [comment]
我也是用的 Linux的环境--- 只不过gvim的字体比较好，于是就偶尔使用GVIM，截图的话，如下：
![pic](http://7xotye.com1.z0.glb.clouddn.com/kvimbug.png)

然后 VIM以及GVIM的 YCM也报错了。。。。

**Comment by wklken** [comment]
现将ycm编译过了再说.....(重新执行一把install.sh即可, 不过YCM下载要等很久)

**Comment by ShomyLiu** [comment]
好，我试试－－－话说之前YCM可以用的。。更新之后需要重新编译，他不是跳过了已安装的插件吗？

**Comment by ShomyLiu** [comment]
.....重新编译安装完成之后。。。。打开  `vim`　出错了。。。。如下，
![bug](http://7xotye.com1.z0.glb.clouddn.com/kvimbug1.png)

**Comment by ShomyLiu** [comment]
![1](http://7xotye.com1.z0.glb.clouddn.com/kvimbug2.png)

**Comment by ShomyLiu** [comment]
安装了futures 之后YCM已经可以了－－　VIM 正常使用了，但是　打开GVIM 还是无法分配颜色错误。。。

**Comment by ShomyLiu** [comment]
在使用中。。也报错了，在 `NORMAL`模式下，　按　`f`　的时候，出如下错误: 
![2](http://7xotye.com1.z0.glb.clouddn.com/cuowu3.png)

google了好长时间。。没找到答案。。麻烦了

**Comment by petrewoo** [comment]
我可以正常使用但是，也会报错，问题来了，设置换下位置之后
let g:qs_first_occurrence_highlight_color = 155
let g:qs_first_occurrence_highlight_color = '#afff5f'
变成了上面这样后，mvim没事儿了，但是vim有事情了（我的vim是 mvim －v）
怀疑这个地方设置是不是要写成判断语句？但是我vim配置方面所知有限，希望抛砖引玉，有达人出来指点下

**Comment by ossphil** [comment]
我的vim也是 mvim -v，但在iterm2下启动vim没问题，输入mvim后会出现下面的错误，还是关于颜色155和81：
```sh
Error detected while processing function <SNR>46_set_highlight_colors[27]..<SNR>46_add_to_highlight_group:
line    1:
E254: Cannot allocate color 155
Error detected while processing function <SNR>46_set_highlight_colors[29]..<SNR>46_add_to_highlight_group:
line    1:
E254: Cannot allocate color 81

E254: Cannot allocate color 155
```

**Comment by wklken** [comment]
@ShomyLiu  

去掉quick-scope

```
" 更高效的行内移动, f/F/t/T, 才触发
" quickscope
Plug 'unblevable/quick-scope'
```
@ShomyLiu  

去掉quick-scope

```
" 更高效的行内移动, f/F/t/T, 才触发
" quickscope
Plug 'unblevable/quick-scope'
```

**Comment by wklken** [comment]
@petrewoo  @ossphil 
去掉 quick_scope 这个插件试试, 看起来是这个导致的

**Comment by ruanyl** [comment]
我下载mvim测试了quick-scope，并不能重现这个问题。看了下quick-scope的代码：https://github.com/unblevable/quick-scope/blob/master/plugin%2Fquick_scope.vim#L87-L109
以及它的文档：
https://github.com/unblevable/quick-scope/blob/master/doc/quick-scope.txt#L102-L125

如果没有设置`g:qs_first_occurrence_highlight_color` 和 `g:qs_first_occurrence_highlight_color`，`quick-scope`默认会根据是否是gui环境来设置颜色。所以我觉得：
https://github.com/wklken/k-vim/blob/master/vimrc.bundles#L432-L435
这几行代码应该更改，因为`quick-scope`默认的颜色就是：
`#afff5f `和`#5fffff`, 和`155`, `81`。其实这几行配置是可以删除的吧。

**Comment by ShomyLiu** [comment]
@ruanyl  好的　我试试　　辛苦了

**Comment by wklken** [comment]
删除试试...那几行看着文档改的, 主要想改个绿色(默认是蓝色)
ok的话发个patch哈

**Comment by ShomyLiu** [comment]
@ruanyl  ok 了，　去掉了之后　就可以了＝＝　问题应该就是他了，估计不能换颜色QAQ

**Comment by wklken** [comment]
提交上去了, 感谢.......暂时注解, 我还是想看看怎么改成绿色的>_<

**Comment by ShomyLiu** [comment]
好的，辛苦了！

**Comment by ShomyLiu** [comment]
another question......; 就是在 `NORMAL` 模式，使用键盘的 左右键切换标签时，会不确定性得，弹出这个东西，按了enter  可以正常使用，请问这个有什么影响没？
![bug](http://7xotye.com1.z0.glb.clouddn.com/bug3.png)
