### ISSUE TITLE
Mac下打开.java文件很慢

### ISSUE THREAD

**Issue by marsqing** [wklken/k-vim#164]
因为是要编译然后提示编译错误吧，怎么disable掉?

**Comment by marsqing** [comment]
找到了，禁止syntastic插件检查java就行了
http://stackoverflow.com/questions/15937042/syntastic-disable-automatic-compilation-of-java

**Comment by ilaipi** [comment]
感谢。ubuntu上也是

**Comment by wklken** [comment]
@marsqing  麻烦发下改动的配置, 我加进去, 或者, 提个patch

**Comment by ilaipi** [comment]
`vimrc.bundles` 大概727行：
```
" let g:syntastic_mode_map = {'mode': 'active', 'passive_filetypes': ['go'] }
```

改为： 

```
let g:syntastic_mode_map = {'mode': 'active', 'passive_filetypes': ['go', 'java'] }
```

**Comment by wklken** [comment]
已提交, 挪到syntastic的配置位置
thx:)
