### ISSUE TITLE
在'NORMAL'模式通过 '<leader>sa' 全选后，'<leader>y'不能复制到剪贴板？

### ISSUE THREAD

**Issue by ilaipi** [wklken/k-vim#168]
左下角显示模式是 `V-LINE`

**Comment by wklken** [comment]
我这边正常的, 什么版本?

,sa => ,y => p

**Comment by ilaipi** [comment]
是要复制到系统剪贴版，可以到其它应用程序ctrl-v

**Comment by ilaipi** [comment]
`VIM - Vi IMproved 7.4`

**Comment by bfwg** [comment]
我这边也有这种问题 就是`,sa`以后 要按一下`hjkl`方向键再按`y`才可以粘贴 我用的mac

**Comment by Leeiio** [comment]
" select all
map <Leader>sa ggVG"

配置里的这个不对吧，应该是ggVG吧，去掉后面的"就好了

**Comment by wklken** [comment]
@Leeiio 提到的, 测了下正确的:)  @ilaipi 可以修改看看
thx @Leeiio

**Comment by ilaipi** [comment]
thanks!!
@wklken @Leeiio
