### ISSUE TITLE
编译Youcompleteme出错，貌似是变量设置问题

### ISSUE THREAD

**Issue by linghutf** [wklken/k-vim#169]
- 编译条件
``` 
./install.py --clang-completer --system-libclang --gocode-completer
```
- 出错信息
```
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Your C++ compiler supports C++11, compiling in that mode.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.10", minimum required is "2.6") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.10", minimum required is "2.6") 
Using libclang to provide semantic completion for C/C++/ObjC
Using external libclang: /home/linghutf/k-vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/TEMP-NOTFOUND
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.10") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/linghutf/k-vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/TEMP
    linked by target "ycm_core" in directory /home/linghutf/k-vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm

-- Configuring incomplete, errors occurred!
See also "/tmp/ycm_build.6En9PS/CMakeFiles/CMakeOutput.log".
See also "/tmp/ycm_build.6En9PS/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/home/linghutf/k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 266, in <module>
    Main()
  File "/home/linghutf/k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 259, in Main
    BuildYcmdLibs( args )
  File "/home/linghutf/k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 218, in BuildYcmdLibs
    subprocess.check_call( [ 'cmake' ] + full_cmake_args )
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-G', 'Unix Makefiles', '-DUSE_CLANG_COMPLETER=ON', '-DUSE_SYSTEM_LIBCLANG=ON', '/home/linghutf/k-vim/bundle/YouCompleteMe/third_party/ycmd/cpp']' returned non-zero exit status 1
```
```

**Comment by wklken** [comment]
in `install.sh`

```
cd $CURRENT_DIR/bundle/YouCompleteMe/
git submodule update --init --recursive
if [ `which clang` ]   # check system clang
then
    bash -x install.sh --clang-completer --system-libclang   # use system clang
else
    bash -x install.sh --clang-completer
fi
```

试下这个, 如果系统已经带了`clang` 使用第一个, 否则, 使用第二个

可以到ycm的issues或者google下错误信息
其实你应该到YCM那边去提issue, k-vim没有做变更

**Comment by linghutf** [comment]
我用的就是第一个，编译条件上面有，奇怪golang的编译成功,c/c++的没有成功。

**Comment by linghutf** [comment]
我觉得应该是你的ycm没有更新导致的，我去看了ycm的代码，其中引起错误的地方是
```
File "/home/linghutf/k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 218, in BuildYcmdLibs
    subprocess.check_call( [ 'cmake' ] + full_cmake_args )
```
subprocess.check_call返回非零值，而作者源代码是:
``
def BuildYcmdLibs( args ):
  build_dir = mkdtemp( prefix = 'ycm_build.' )

  try:
    full_cmake_args = [ '-G', GetGenerator( args ) ]
    if OnMac():
      full_cmake_args.extend( CustomPythonCmakeArgs() )
    full_cmake_args.extend( GetCmakeArgs( args ) )
    full_cmake_args.append( p.join( DIR_OF_THIS_SCRIPT, 'cpp' ) )

    os.chdir( build_dir )
    subprocess.check_call( [ 'cmake' ] + full_cmake_args )

    build_target = ( 'ycm_support_libs' if 'YCM_TESTRUN' not in os.environ else
                     'ycm_core_tests' )

    build_command = [ 'cmake', '--build', '.', '--target', build_target ]
    if OnWindows():
      build_command.extend( [ '--config', 'Release' ] )
    else:
      build_command.extend( [ '--', '-j', str( NumCores() ) ] )

    subprocess.check_call( build_command )

    if 'YCM_TESTRUN' in os.environ:
      RunYcmdTests( build_dir )
  finally:
    os.chdir( DIR_OF_THIS_SCRIPT )
    rmtree( build_dir )
```
你集成的代码:
```
def BuildYcmdLibs( args ):
S>  4   build_dir = mkdtemp( prefix = 'ycm_build.' )
    3    
S>  2   try:
S>  1     full_cmake_args = [ '-G', GetGenerator( args ) ]
  212     if OnMac():                                                                                           
S>  1       full_cmake_args.extend( CustomPythonCmakeArgs() )
S>  2     full_cmake_args.extend( GetCmakeArgs( args ) )
S>  3     full_cmake_args.append( p.join( DIR_OF_THIS_SCRIPT, 'cpp' ) )
    4    
S>  5     os.chdir( build_dir )
S>  6     subprocess.check_call( _[ _'cmake'_ ] + full_cmake_args_ )
    7    
S>  8     build_target = ( 'ycm_support_libs' if 'YCM_TESTRUN' not in os.environ else
S>  9                      'ycm_core_tests' )
```
两者不一样的,或许你可以更新一下集成

**Comment by wklken** [comment]
`k-vim`没有集成任何代码, 所有插件都是在安装的时候到github源下载的最新代码
