### ISSUE TITLE
打开go源文件太慢了 希望能够改进下

### ISSUE THREAD

**Issue by a598799539** [wklken/k-vim#173]
一个40来行的代码也要四五秒，配置是mac pro 8 GB . 希望改进下 谢谢

**Comment by wklken** [comment]
我测试过mac/ubuntu/centos都是ok的, 基本秒开

确定下是否开启了golang bundle组件, 开启了的话, 确认vim-go是否安装 chenggong
然后, 确认下是否插件syntastic检查golang语法造成的.....

麻烦定位下是哪个插件的问题.

**Comment by a598799539** [comment]
我是直接根据readme安装的

**Comment by a598799539** [comment]
@wklken 看bundle中确实没有vim-go

**Comment by wklken** [comment]
@a598799539  
https://github.com/wklken/k-vim/issues/164  看下是不是这个

如果还不行, 上二分法, 定位下哪个插件

**Comment by a598799539** [comment]
没有自动安装vim-go这个有影响吗

**Comment by a598799539** [comment]
确实加上vimrc 加上这句`let g:syntastic_mode_map = {'mode': 'active', 'passive_filetypes': ['go', 'java'] }
`就快多了

**Comment by wklken** [comment]
看来是syntastic的锅, 不过我这边开着没感觉......
vim-go可以开启下, 按照文档装下, 毕竟自动补全什么的还是要的

**Comment by Zhang21** [comment]
> 没有自动安装vim-go这个有影响吗

在 `vimrc.bundles`中，在这里面加上golang

```
let g:bundle_groups=
```
