### ISSUE TITLE
macvim-snapshot-88问题

### ISSUE THREAD

**Issue by gatspy** [wklken/k-vim#175]
看到9.1更新以后，手痒brew upgrade macvim到最新的88,结果悲剧了。
airline的状态栏宽度和terminal的宽度不一致。gvim中状态栏显示各种按钮字体。
恢复到87以后 一切恢复正常，折腾了好久，恢复到9.0又到9.1的各种折腾。
系统对遇到同样问题的朋友有帮助。
谢谢k-vim~~~

**Comment by wklken** [comment]
vimrc中有statusline配置
另外有插件 airline, 可以看下官方github

自行调试下吧
