### ISSUE TITLE
无法创建工作区目录权限不够如何解决？

### ISSUE THREAD

**Issue by zhangity** [wklken/k-vim#177]
在sh -x install.sh后一直有十几个插件是下载不动的，:PlugInstall  后显示 fatal 安装目录 无法创建工作区目录权限不够 该如何解决？非常感谢！

**Comment by zhangity** [comment]
补充一下，已经是在 root 权限执行的

**Comment by wklken** [comment]
可以确认下 Plug 插件的安装 是否有解决方法......
https://github.com/junegunn/vim-plug
