### ISSUE TITLE
安装vim bundle过程中，会卡在vim-textobj-indent位置，从而不能完成安装。

### ISSUE THREAD

**Issue by uinika** [wklken/k-vim#178]
你最近更新过之后，我进入k-vim目录执行sh安装时，安装进度会停止在vim-textobj-indent位置，然后就卡住不动了。这个我已经测试多次，和网速无关，是否vim bundle里配置存在问题？希请朋友检视一下，你这份vim配置非常好用。

**Comment by uinika** [comment]
Searching for unused plugins in /home/hank/.vim/bundle                                          |
[=============================================]                                                 |~                                                                                              
                                                                                                |~                                                                                              
- /home/hank/.vim/bundle/Vim-Jinja2-Syntax/                                                     |~                                                                                              
- /home/hank/.vim/bundle/YouCompleteMe/                                                         |~                                                                                              
- /home/hank/.vim/bundle/ctrlp.vim/                                                             |~                                                                                              
- /home/hank/.vim/bundle/delimitMate/                                                           |~                                                                                              
- /home/hank/.vim/bundle/gundo.vim/                                                             |~                                                                                              
- /home/hank/.vim/bundle/molokai/                                                               |~                                                                                              
- /home/hank/.vim/bundle/python-syntax/                                                         |~                                                                                              
- /home/hank/.vim/bundle/syntastic/                                                             |~                                                                                              
- /home/hank/.vim/bundle/tagbar/                                                                |~                                                                                              
- /home/hank/.vim/bundle/vim-colors-solarized/                                                  |~                                                                                              
- /home/hank/.vim/bundle/vim-ctrlspace/                                                         |~                                                                                              
- /home/hank/.vim/bundle/vim-markdown/                                                          |~                                                                                              
- /home/hank/.vim/bundle/vim-python-pep8-indent/                                                |~                                                                                              
- /home/hank/.vim/bundle/vim-quickrun/                                                          |~                                                                                              
- /home/hank/.vim/bundle/vim-signature/                                                         |~                                                                                              
- /home/hank/.vim/bundle/vim-surround/                                                          |~                                                                                              
- /home/hank/.vim/bundle/vim-textobj-indent/     TIPS:卡在了这个位置。

**Comment by wklken** [comment]
新版本用的Plug作为插件管理, 并发去下载安装插件, 跟配置无关
你可以去掉vim-textobj-indent插件配置, 重新安装试试
