### ISSUE TITLE
新版本的k-vim如何主动显示python中的语法错误？

### ISSUE THREAD

**Issue by chenjie2014** [wklken/k-vim#180]
新版本的k-vim不能用>>和>高亮出python中的错误了，主动用leader+s一直卡在:call ToggleErros

**Comment by wklken** [comment]
默认是有高亮的, 确认下所有插件安装成功, 特别是syntastic

**Comment by chenjie2014** [comment]
![image](https://cloud.githubusercontent.com/assets/10704040/12220993/926afe24-b7c3-11e5-85bc-d9d91e9cd40d.png)
syntastic显示是已经安装完成的，并且在安装的中途也没有报错误

**Comment by chenjie2014** [comment]
![image](https://cloud.githubusercontent.com/assets/10704040/12221009/8d24c746-b7c4-11e5-8bb9-e9729bae1e30.png)
syntastic显示是状态是OK，其他组件也都是OK状态

**Comment by wklken** [comment]
无法复现, 重新走了下centos/ubuntu/mac的安装流程, 一切正常
syntastic会将错误的语法飘红展示

你需要自己尝试调试下
