### ISSUE TITLE
Color theme for Monokai 状态栏

### ISSUE THREAD

**Issue by bfwg** [wklken/k-vim#182]
<img width="1015" alt="screen shot 2016-01-15 at 3 17 42 pm" src="https://cloud.githubusercontent.com/assets/12819525/12367919/27eab72a-bb9b-11e5-86d3-e85257d4c913.png">
这个是light 
![image](https://cloud.githubusercontent.com/assets/12819525/12367925/3bbad474-bb9b-11e5-81b4-f96ecf9aae2d.png)
这个是monokai
不知道为什么 状态栏颜色很不对 就是normal insert 那里，我用的是iterm 在mac上。
求帮助！

**Comment by wklken** [comment]
airline, 去找官方github上, 自行自定义配下就行

**Comment by bfwg** [comment]
谢谢你
