### ISSUE TITLE
v选定之后用<<排缩进， 没有办法用.来重复进行缩进

### ISSUE THREAD

**Issue by Alexniver** [wklken/k-vim#187]
不习惯用=来排缩进， 习惯用v j <<加.来排缩进, 但现在vj选定之后， << 缩进之后， 按.没反应。这个是哪里设置的问题吗？

**Comment by wklken** [comment]
原来，缩进后会退出选中。k-vim目前配置选中缩进后会自动再次选中，最后一个动作不是缩进
On 02/15/2016 11:41, Alexniver wrote:

不习惯用=来排缩进， 习惯用v j <<加.来排缩进, 但现在vj选定之后， << 缩进之后， 按.没反应。这个是哪里设置的问题吗？

**Comment by wklken** [comment]
具体配置是 `.vimrc`中, 需要的话自行去除

```
" 调整缩进后自动选中，方便再次操作
vnoremap < <gv
vnoremap > >gv
```
