### ISSUE TITLE
请问一下注释功能如何使用啊？

### ISSUE THREAD

**Issue by bwangel23** [wklken/k-vim#193]
我看`vimrc.bundles`中用的是`nerdcommenter`插件来注释，可是我看`nerdcommenter`的README中说这个插件中提供的是`Key mapping`,必须映射了才能使用!

请问一下这些`Key mapping`映射到哪个键上了啊，还是需要我自己设置？

**Comment by wklken** [comment]
`,cc` / `,cu`
没有单独配置的使用的是对应插件默认的快捷键

**Comment by bwangel23** [comment]
请问这个是在哪个文件里配置的啊？

**Comment by wklken** [comment]
grep in .vim dir or google it yourself.

**Comment by wklken** [comment]
自行查看对应插件的官方文档
