### ISSUE TITLE
编写完保存后再次进行编辑时，会出现下划线并且报错。

### ISSUE THREAD

**Issue by ScarecrowFu** [wklken/k-vim#197]
![2016-03-02 21 29 32](https://cloud.githubusercontent.com/assets/10743090/13461667/e5f9e65e-e0bd-11e5-8068-19e9ff689d32.png)

如图所示，但是直接复制代码并没有那些下划线：
    
   15 parser.add_argument('file')
S> 14 parser.add_argument('-o','--output')
S> 13 parser.add_argument('--width',type=int,default=80)
S> 12 parser.add_argument('--height',type=int,default=80)
   11      
   10 args = parser.parse_args()
    9      
    8 IMG = args.file
    7 OUTPUT = args.output
    6 WIDTH = args.width
    5 HEIGHT = args.height
    4      
    3 accii_list = list("!@#$%^&*()~{}|:abcdefg0123456789")
    2      
S>  1 def get_list(r,b,g,alpha=256):
  26      if alpha == 0:                                                                                                                              
S> 14 parser.add_argument('-o','--output')
S> 13 parser.add_argument('--width',type=int,default=80)
S> 12 parser.add_argument('--height',type=int,default=80)

**Comment by wklken** [comment]
代码风格检查插件高亮显示的, 不是报错, 不符合规范而已
syntastic, 不需要的话去掉
