### ISSUE TITLE
vim 打开文件时,出现"处理 function <SNR>162_OnBufferVisit..<SNR>162_OnFileReadyToParse 时发生错误"

### ISSUE THREAD

**Issue by yds629** [wklken/k-vim#198]
### Traceback (most recent call last):
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
  File "<string>", line 1, in <module>
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
  File "/home/sam/download/k-vim/bundle/YouCompleteMe/autoload/../python/ycm/you
completeme.py", line 266, in OnFileReadyToParse
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
    self._AddSyntaxDataIfNeeded( extra_data )
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
  File "/home/sam/download/k-vim/bundle/YouCompleteMe/autoload/../python/ycm/you
completeme.py", line 623, in _AddSyntaxDataIfNeeded
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
    syntax_parse.SyntaxKeywordsForCurrentBuffer() )
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
  File "/home/sam/download/k-vim/bundle/YouCompleteMe/autoload/../python/ycm/syn
tax_parse.py", line 93, in SyntaxKeywordsForCurrentBuffer
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
    return _KeywordsFromSyntaxListOutput( syntax_output )
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
  File "/home/sam/download/k-vim/bundle/YouCompleteMe/autoload/../python/ycm/syn
tax_parse.py", line 97, in _KeywordsFromSyntaxListOutput
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
    group_name_to_group = _SyntaxGroupsFromOutput( syntax_output )
请按 ENTER 或其它命令继续
处理 function youcompleteme#Enable..<SNR>162_OnBufferVisit..<SNR>162_OnFileReady
ToParse 时发生错误:
第   13 行:
  File "/home/sam/download/k-vim/bundle/YouCompleteMe/autoload/../python/ycm/syn
tax_parse.py", line 113, in _SyntaxGroupsFromOutput

**Comment by wklken** [comment]
打开什么类型的文件?
先注掉YCM再打开, 确认下是否报错

然后重新编译安装下YCM试试

**Comment by yds629** [comment]
打开.py和.cc都有这样的错误提示，但文件能打开，YCM似乎也能运行。注释掉YCM则没有这样的错误提示。重装并没有用。谢谢@@

在 2016-03-08 23:34:07，"wklken" <notifications@github.com> 写道：


打开什么类型的文件?
先注掉YCM再打开, 确认下是否报错

然后重新编译安装下YCM试试

**Comment by wklken** [comment]
那你只能去YCM的github看看能否找到解决方案了.
或者, 放弃掉YCM, 不过YCM是很给力的一个插件
