### ISSUE TITLE
自动补全引号

### ISSUE THREAD

**Issue by hominlinx** [wklken/k-vim#2]
"自动补全单引号，双引号等 Bundle 'underlog/ClosePairs'
Bundle 'Raimondi/delimitMate'
这个插件在使用的时候,会出现以下问题：
i < 10;
他会自动加入<> ,应该如何处理啊？

**Comment by xushaobo** [comment]
求怎么能在补全的括号后直接插入,shift-tab不起作用。。。

**Comment by xushaobo** [comment]
嗯，谢谢，可以了

在 2015年8月28日 下午11:05，wklken <notifications@github.com>写道：
