### ISSUE TITLE
要让solarized主题正确显示必须要给终端装上solarized的主题么？

### ISSUE THREAD

**Issue by Leeiio** [wklken/k-vim#205]
我试了下发现不管是light还是dark，如果不给终端装上solarized的相应主题配色，显示的颜色永远不是符合预期的那样。比如light的
![2016-03-30 9 20 00](https://cloud.githubusercontent.com/assets/218127/14143312/30378162-f6bd-11e5-94dc-9d0255de483e.png)
背景色不对，应该是这样
![2016-03-30 9 21 12](https://cloud.githubusercontent.com/assets/218127/14143348/5effc964-f6bd-11e5-98a2-6b1863a8d967.png)

下图是macvim的，很明显这两个的背景色不一样... 除了给终端装solarized主题外有别的办法么？

**Comment by lovelock** [comment]
不知道你用的是不是iTerm，苹果自带的终端对256配色的支持貌似有问题。我试了把iTerm改成solarized light配色，vim用的dark配色，没有问题。——我用的是从k-vim自己fork后修改的，不知道k-vim现在怎么样了

**Comment by Leeiio** [comment]
@lovelock 是iTerm，我的意思是solarized这个配色只是在vim里设置的话在iTerm下显示会和MacVim不一致
