### ISSUE TITLE
注释问题

### ISSUE THREAD

**Issue by waylovin** [wklken/k-vim#206]
使用shift + V 选中内容后使用,cc进行注释的时候会失败，变成了剪切，估计是和其他的快捷键冲突了。有没有解决办法？

**Comment by wklken** [comment]
测试了下注释是正常的....

```
,cc
shift+v ,cc
```

PS: `,cc`要按得足够快, 如果`,c`然后停一下...就变成剪切了

所以, 先确认下, 如果还是存在问题, 看下你是否装了其他插件, 使用二分法注解排查

**Comment by waylovin** [comment]
刚试了下，果然...姿势和力道同样重要...谢谢啦

**Comment by jnjaby** [comment]
@wklken 请问怎么快速取消注释呢

**Comment by wklken** [comment]
同样的键, 是个toggle, 注释+解注释
