### ISSUE TITLE
python3语法不支持？

### ISSUE THREAD

**Issue by airborne007** [wklken/k-vim#208]
`python3`语法好像识别不出来，一些新的语法，如`yield from`会被检测为语法错误，请问这个问题该怎么解决？

**Comment by wklken** [comment]
k-vim目前配置是不支持python3的
你可以看下syntastic这个插件的faq, 改下配置就行

[faq](https://github.com/scrooloose/syntastic#4-faq) => 4.2

```
let g:syntastic_python_python_exec = '/path/to/python3'
```
