### ISSUE TITLE
ubuntu 16.04 YouCompletme 彻底奔溃了

### ISSUE THREAD

**Issue by yech1990** [wklken/k-vim#209]
> ubuntu 16.04 系统默认是py3了
```bash
 File "/home/conf_file/k-vim/bundle/YouCompleteMe/autoload/../python/ycm/setup.
py", line 49, in SetUpYCM
```

- [X] 重新编译Youcompletme
 不能解决问题, 分别试了``python3 install.py`` ``python2 install.py``
- [ ] 重新安装k-vim
 也是不能解决问题

**Comment by wklken** [comment]
关注下YCM 那边的进度吧

https://github.com/Valloric/YouCompleteMe/issues/2002

**Comment by yech1990** [comment]
现在还是静悄悄 目测不会太快

**Comment by yech1990** [comment]
没看懂 YCM那边的意思, 怎么看起来像是说解决了, 可pull到最新还是完全奔溃了

希望先把issue开了

**Comment by shenxs** [comment]
http://stackoverflow.com/questions/20160902/how-to-solve-requires-python-2-x-support-in-linux-vim-and-it-have-python-2-6-6
亲测解决了这个问题
