### ISSUE TITLE
建议增加ycm的一个变量

### ISSUE THREAD

**Issue by ListenerRi** [wklken/k-vim#211]
有些系统默认的python版本是2.x,有些是3.x,也就是说/bin/python可能是python2的链接文件也可能是python3的链接文件
在arch下默认的是python3,直接执行./install.py来编译ycm,也就是说使用了3.x的python,然后打开vim的时候,vim可能会使用2.x的python,这就导致ycm无法使用并抛出异常,下面是官方的一些解释:

> I get _ImportError_ exceptions that mention 'PyInit_ycm_core' or 'initycm_core'
> 
> These errors are caused by building the YCM native libraries for Python 2 and
> trying to load them into a Python 3 process (or the other way around).
> 
> For instance, if building for Python 2 but loading in Python 3:
> 
> ```
> ImportError: dynamic module does not define init function (PyInit_ycm_core)
> ```
> 
> If building for Python 3 but loading in Python 2:
> 
> ```
> ImportError: dynamic module does not define init function (initycm_core)
> ```
> 
> Setting the |g:ycm_server_python_interpreter| option to force the use of a
> specific Python interpreter for 'ycmd' is usually the easiest way to solve the
> problem. Common values for that option are '/usr/bin/python' and
> '/usr/bin/python3'.

所以,我觉得如果增加这一条配置,可能会避免这一冲突(至少我这里发生了冲突archlinux):

```
let g:ycm_server_python_interpreter = 'python'
```

直接设置为python,就可以确保编译时所使用的python和vim调用的python版本一样

**Comment by gatspy** [comment]
我是用pyenv管理virtualenv，在配置文件里也加入
let g:ycm_server_python_interpreter = 'python'
let g:ycm_path_to_python_interpreter = '/usr/local/var/pyenv/versions/py3/bin/python'
但是在vim里F10的时候使用的还是安装ycm的时候使用的系统python

**Comment by wklken** [comment]
F10, 用的是quickrun插件, 应该也可配置

**Comment by gatspy** [comment]
vim version 里python3是- 是不是在vim就不知道用python3写代码呢？

**Comment by wklken** [comment]
https://github.com/Valloric/YouCompleteMe#python-semantic-completion
