### ISSUE TITLE
复制粘贴问题

### ISSUE THREAD

**Issue by jcppython** [wklken/k-vim#213]
如何 复制/粘贴 到不同的寄存器?
特别时如何粘贴系统剪贴板(+寄存器)中的内容?

谢谢

**Comment by wklken** [comment]
`k-vim`目前没有对复制粘贴进行优化, 所以提到的问题, 需要查询vim原生如何进行操作即可, 自行google下

**Comment by jcppython** [comment]
尝试了下[vim-easyclip](https://github.com/svermeulen/vim-easyclip)，可以考虑下~
