### ISSUE TITLE
求问小问题，求大神带

### ISSUE THREAD

**Issue by lokistone** [wklken/k-vim#216]
![image](https://cloud.githubusercontent.com/assets/10117199/14603879/f0060d1c-05a2-11e6-820a-dfeba3bc82ad.png)

![image](https://cloud.githubusercontent.com/assets/10117199/14603925/4127a07a-05a3-11e6-8434-ed8d58e3dbe4.png)

![image](https://cloud.githubusercontent.com/assets/10117199/14603932/53a7d058-05a3-11e6-8811-55a8a9d52b09.png)

然后我brew install vim 说更新下vim的版本，可是发现各种报错不行啊，话说求大神带啊，要是能链接到macvim也行啊

**Comment by wklken** [comment]
安装好macvim
确认版本是7.4 mvim --version 
加一个alias到 .bashrc/.bash_profile/.zshrc(自行根据自己使用的shell配置)

```
vim='mvim -v'
```

=============

如果想自己编译, 也行
如何编译vim, 可以看看youcompleteme的github readme, 上面有入口, 一步步照做就行

============

仔细看文档 & 善用google
