### ISSUE TITLE
安装的时候有点问题

### ISSUE THREAD

**Issue by fangqian** [wklken/k-vim#217]
sh -x install.sh 
+ dirname install.sh
+ BASEDIR=.
+ cd .
+ pwd
+ CURRENT_DIR=/home/fangqian/k-vim
+ echo Step1: backing up current vim config
Step1: backing up current vim config
+ date +%Y%m%d
+ today=20160419
+ [ -e /home/fangqian/.vim ]
+ [ ! -L /home/fangqian/.vim ]
+ [ -e /home/fangqian/.vimrc ]
+ [ ! -L /home/fangqian/.vimrc ]
+ [ -e /home/fangqian/.gvimrc ]
+ [ -e /home/fangqian/.vimrc.bundles ]
+ [ ! -L /home/fangqian/.vimrc.bundles ]
+ [ -L /home/fangqian/.vim ]
+ unlink /home/fangqian/.vim
+ [ -L /home/fangqian/.vimrc ]
+ unlink /home/fangqian/.vimrc
+ [ -L /home/fangqian/.gvimrc ]
+ [ -L /home/fangqian/.vimrc.bundles ]
+ unlink /home/fangqian/.vimrc.bundles
+ echo Step2: setting up symlinks
Step2: setting up symlinks
+ lnif /home/fangqian/k-vim/vimrc /home/fangqian/.vimrc
+ [ -e /home/fangqian/k-vim/vimrc ]
+ ln -sf /home/fangqian/k-vim/vimrc /home/fangqian/.vimrc
+ lnif /home/fangqian/k-vim/vimrc.bundles /home/fangqian/.vimrc.bundles
+ [ -e /home/fangqian/k-vim/vimrc.bundles ]
+ ln -sf /home/fangqian/k-vim/vimrc.bundles /home/fangqian/.vimrc.bundles
+ lnif /home/fangqian/k-vim/ /home/fangqian/.vim
+ [ -e /home/fangqian/k-vim/ ]
+ ln -sf /home/fangqian/k-vim/ /home/fangqian/.vim
+ echo Step3: update/install plugins using Vundle
Step3: update/install plugins using Vundle
+ system_shell=/bin/bash
+ export SHELL=/bin/sh
+ vim -u /home/fangqian/.vimrc.bundles +PlugInstall! +PlugClean! +qall
处理 /home/fangqian/.vimrc.bundles 时发生错误:
第  496 行:
E117: 未定义的函数: expand_region#custom_text_objects
请按 ENTER 或其它命令继续

**Comment by wklken** [comment]
目测是vim版本导致的, 提供下你的vim版本信息

**Comment by fangqian** [comment]
现在好了，我先执行了下bash。然后执行安装命令就可以了 发自网易邮箱大师 在2016年04月19日 14:37 ，wklken写道： 目测是vim版本导致的, 提供下你的vim版本信息 — You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub

**Comment by fangqian** [comment]
现在安装好了，执行安装命令之前，先执行了bash。之后就好了 发自网易邮箱大师 在2016年04月19日 14:37 ，wklken写道： 目测是vim版本导致的, 提供下你的vim版本信息 — You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub
