### ISSUE TITLE
airline 箭头处显示不正常

### ISSUE THREAD

**Issue by chy373** [wklken/k-vim#218]
![screen shot 2016-04-21 at 11 03 52 am](https://cloud.githubusercontent.com/assets/5926064/14696817/c443ca10-07b0-11e6-9839-d3b07c95a196.png)

iterm字体用的是source code pro for powline

**Comment by chy373** [comment]
![screen shot 2016-04-21 at 11 21 43 am](https://cloud.githubusercontent.com/assets/5926064/14697077/4b7ec8b6-07b3-11e6-9f0d-42f5637778cc.png)

tmux显示正常

**Comment by wklken** [comment]
是哪个位置不正常呢? 两张图vim显示的箭头是一致的, 只是下面这张由于少了git的分支信息, 缺了一列....

**Comment by yech1990** [comment]
应该说的是三角形的大小

**Comment by yech1990** [comment]
确实是有问题 我之前用了这么久一直没注意到

**Comment by chy373** [comment]
嗯 对的 我说的是三角形的大小

**Comment by chy373** [comment]
我的系统是mac vim版本7.4 终端iterm2
不知道问题出在哪

**Comment by LittleKey** [comment]
我刚才装了一个iterm2，感觉剪头是正常的

![screen_shoot](https://raw.githubusercontent.com/LittleKey/gallery/master/test.png)

环境
- vim 7.4 `theme: Tomorrow Night Bright`
- iterm2 2.1.4 `theme: Tomorrow Night Bright`
- mac 10.11.3

**Comment by ruanyl** [comment]
是不是少了
```
let g:airline_powerline_fonts = 1
````

**Comment by chy373** [comment]
@ruanyl 没有少 我加了 @LittleKey  其实仔细看 箭头还是偏小 和我tmux配置的主题上那种箭头还是有很大区别

**Comment by wklken** [comment]
囧...用了那么久没注意过...

vimrc.bundles 602行附近, 我对airline的符号进行了替换

```
" airline {{{
    if !exists('g:airline_symbols')
        let g:airline_symbols = {}
    endif
    let g:airline_left_sep = '▶'
    let g:airline_left_alt_sep = '❯'
    let g:airline_right_sep = '◀'
    let g:airline_right_alt_sep = '❮'
    let g:airline_symbols.linenr = '¶'
    let g:airline_symbols.branch = '⎇'
    " 是否打开tabline
    " let g:airline#extensions#tabline#enabled = 1
" }}}
```

可以注掉/自行修改测试一下, 可能不同字体下展现会有差异吧

**Comment by chy373** [comment]
@wklken  嗯 果然 全部注释掉就正常了 多谢！

**Comment by wklken** [comment]
@chy373 
自定义是为了防止没装对应字体的人可以正常使用.....

**Comment by yech1990** [comment]
注释掉后字体更怪了 变成一个大于号 >

**Comment by wklken** [comment]
到airline的github上看看自定义的方法吧
