### ISSUE TITLE
光标在命令模式之下无法移动

### ISSUE THREAD

**Issue by deadking01** [wklken/k-vim#221]
安装好vim之后，光标在命令模式之下无法移动，而且行号显示好像也不正常。
能帮着修正一下吗？

**Comment by wklken** [comment]
命令行模式, 光标本身就看不到了, 底栏命令行, `ctrl+a/e`或者左右方向键可以在输入的命令中移动
编辑模式下, 默认方向键禁用的, 使用hjkl移动, 看文档吧

行号, 默认是相对行号, 怎么改或者禁用, 看文档吧........

**Comment by deadking01** [comment]
收到，好的，非常感谢。
