### ISSUE TITLE
<leader>p　搜索文件的时候，　能不能做到更新目录的文件呢？

### ISSUE THREAD

**Issue by ShomyLiu** [wklken/k-vim#225]
<leader>p 搜索文件时，默认都是打开vim前的文件，如果编辑过程中　新建的文件，就无法搜索到，能不能想nerdtree那样刷新呢？

**Comment by wklken** [comment]
ctrlp还有另一个, `leader+f`,  这个可以找到最近打开或者新建的....二者组合基本够用

这两个组合的缺点, 就是你在外头用其他工具新建的文件, 搜索不到
至于是否支持主动更新, 去看看ctrlp的官方doc是不是有这功能吧

**Comment by wklken** [comment]
..........原来是有的啊

调出ctrlp, 然后F5

```
Press <F5> to purge the cache for the current directory to get new files, remove deleted files and apply new ignore options.
```

**Comment by ShomyLiu** [comment]
啊，　真是麻烦你啦！　以后多看看官方文档！
