### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by ziv-chan** [wklken/k-vim#226]
处理 /home/ziv-chan/.vimrc.bundles 时发生错误:
第  496 行:
E117: 未定义的函数: expand_region#custom_text_objects

**Comment by ziv-chan** [comment]
错误提示：
　　　　python: can't open file 'install.py': [Errno 2] No such file or directory
　　　　+ echo Install Done!

第一次用github

**Comment by zhjawe** [comment]
我也是这两个错误，系统是Ubuntu 16.04（包括32位和64位）。

**Comment by wklken** [comment]
前面插件没安装完, YCM 非常大, 没下载完, 然后进入后续步骤走不下去

找个网速快点的地方, 重新执行下install.sh, 耐心等所有插件安装成功
