### ISSUE TITLE
自动补全出现，HTTPError 500 error

### ISSUE THREAD

**Issue by tongtie** [wklken/k-vim#227]
错误信息如下：
```
HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:544
15/completions
Press ENTER or type command to continue
```
何时出现：输入没有匹配到的内容就会出现，比如: 
输入：
```
sys.stdout 时，sys可以匹配到，stdout就匹配不到了，就会出现如上的错误。
```
环境：
ubuntu14.04
python2.7
配置k-vim按照主页配置的。

**Comment by wklken** [comment]
YCM 报的错, 就提供的信息没法查到有用信息
查看下ycm日志吧, 不行的话重新编译安装下YCM, 还有问题, 到 YCM 的github上提issue

**Comment by hicris** [comment]
我也是同样的问题，依然没有解决，但是可以试试 :set cmdheight=2
这样就不会出现Press ENTER or type command to continue
