### ISSUE TITLE
只拷贝了vimrc文件到本地，安装插件后语法不高亮

### ISSUE THREAD

**Issue by smartczy** [wklken/k-vim#228]
hi：
 我只拷贝了项目中的vimrc文件到我的.vimrc文件中，并安装了vundle用来管理插件，安装好vim-go插件后，打开go文件仍然不高亮，不知道什么原因。而且用vim打开一般的文件，它的高亮也感觉怪怪的。

![image](https://cloud.githubusercontent.com/assets/7263718/15037861/247ca1ec-12d1-11e6-8d0f-684058813592.png)
![image](https://cloud.githubusercontent.com/assets/7263718/15037869/3c29266c-12d1-11e6-95a3-6354c8433b3b.png)

**Comment by wklken** [comment]
1. 检查vundle声明代码放的位置对不对, 具体见vundle官方readme
2. 检查插件安装是否都ok

这个只能自行调试
