### ISSUE TITLE
如果代码中带有需要用户输入的函数时（raw_input/input）会提示以下错误 EOFError: EOF when reading a line

### ISSUE THREAD

**Issue by ziv-chan** [wklken/k-vim#230]
如题，百度了一圈，都说是sublimeText插件问题，可在vim下怎么解决？？

**Comment by wklken** [comment]
给出报错的示例代码, 只看以上信息, 无法定位问题

**Comment by LittleKey** [comment]
你说的是在vim下运行python代码时出的错吧, 目测是quickrun的问题呢。。

**Comment by ziv-chan** [comment]
是的，quickrun的问题...

**Comment by ziv-chan** [comment]
ubuntu16.04LTS,vim7.4
![Uploading 2016-05-09 16-29-56屏幕截图.png…]()
正如LittleKey说的，是quickrun的问题，感谢

**Comment by wklken** [comment]
文档: https://github.com/thinca/vim-quickrun/blob/master/doc/quickrun.txt
关键字: outputter

自行切换测试下
