### ISSUE TITLE
不要太会用，这个错误是怎么回事啊？

### ISSUE THREAD

**Issue by wangx2** [wklken/k-vim#231]
处理 /home/pi/.vimrc.bundles 时发生错误:
第  496 行:
E117: Unknown function: expand_region#custom_text_objects
处理 /home/pi/.vimrc 时发生错误:
第  666 行:
E185: Cannot find color scheme 'solarized'
UltiSnips requires py >= 2.7 or py3
YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support
处理 /home/pi/down/k-vim/bundle/vim-textobj-entire/plugin/textobj/entire.vim 时发生错误:
第   44 行:
E117: Unknown function: textobj#user#plugin
处理 /home/pi/down/k-vim/bundle/vim-textobj-indent/plugin/textobj/indent.vim 时发生错误:
第   48 行:
E117: Unknown function: textobj#user#plugin
请按 ENTER 或其它命令继续

**Comment by wklken** [comment]
```
UltiSnips requires py >= 2.7 or py3
```

善用搜索 https://github.com/wklken/k-vim/issues/219

自行编译vim吧
