### ISSUE TITLE
E117: Unknown function: expand_region#custom_text_objects

### ISSUE THREAD

**Issue by programes** [wklken/k-vim#232]
cygwin 下编译install.sh 报错
Step1: backing up current vim config
Step2: setting up symlinks
Step3: update/install plugins using Vundle
处理 /home/admin/.vimrc.bundles 时发生错误:
第  496 行:
E117: Unknown function: expand_region#custom_text_objects

**Comment by wklken** [comment]
Vundle已经弃用了.....最新版本使用的vim-plug, 并行安装插件

或者, 可以重新执行install.sh, 确保进入了vim, 并且安装完所有插件后自动退出(中途不要人为退出)

**Comment by MingqingLi** [comment]
那就把这段配置** 删除？ 免得给人造成疑惑！

**Comment by wklken** [comment]
新版本已修复, 待发布, `vimrc.bundles`中 加判断

```
    if exists("*expand_region#custom_text_objects")
        call expand_region#custom_text_objects({
        \ 'a]' :1,
        \ 'ab' :1,
        \ 'aB' :1,
        \ 'ii' :0,
        \ 'ai' :0,
        \ })
    endif
```
