### ISSUE TITLE
开了语法高亮以后,vim 卡顿

### ISSUE THREAD

**Issue by tinytub** [wklken/k-vim#233]
iterm2里用 vim 打开 golang 的文件.jk滚动的时候会有卡顿.
系统自带终端要好一点.
可能会是 iterm2的配置造成的吗?
另外syntax off 的话会非常流畅

**Comment by wklken** [comment]
https://github.com/wklken/k-vim/issues/173

**Comment by wklken** [comment]
目测还没提交到版本库, 下一个小版本发布

**Comment by tinytub** [comment]
果然加了这句瞬间流畅了! 
let g:syntastic_mode_map = {'mode': 'active', 'passive_filetypes': ['go', 'java'] }

**Comment by tinytub** [comment]
大意了...刚才流畅了是跟之前的 spf13 搞混了.golang 依然卡顿.我看看我这边是什么造成的.

**Comment by tinytub** [comment]
逐个关闭插件无果.
最后注掉 vim-go 的语法高亮就好了...
"    let g:go_highlight_functions = 1
"    let g:go_highlight_methods = 1
"    let g:go_highlight_structs = 1
"    let g:go_highlight_operators = 1
"    let g:go_highlight_build_constraints = 1

**Comment by tinytub** [comment]
参考 https://github.com/fatih/vim-go/issues/145
最后在 vimrc 中这样搞了.
if &filetype == 'go'
set nocursorcolumn
syntax sync minlines=256
set re=1
endif

**Comment by zx1986** [comment]
好像在 Ruby 也有類似的問題。
https://github.com/spf13/spf13-vim/issues/383
http://stackoverflow.com/questions/16902317/vim-slow-with-ruby-syntax-highlighting

**Comment by wklken** [comment]
- 推荐 ale, 前提是你升级了vim8
- 提前给下ale配置, 稍晚更新patch

```viml
" ale {{{
if has_key(g:plugs, 'ale')
    " pip install flake8
    " npm install -g eslint eslint-plugin-standard eslint-plugin-promise eslint-config-standard
    " npm install -g eslint-plugin-import eslint-plugin-node eslint-plugin-html babel-eslint
    let g:ale_linters = {
    \   'python': ['flake8'],
    \   'javascript': ['eslint'],
    \}

    " E501 -> 120 chars
    let g:ale_python_flake8_args="--ignore=E114,E116,E131 --max-line-length=120"
    " --ignore=E225,E124,E712,E116

    let g:ale_sign_error = '>>'
    let g:ale_sign_warning = '>'

    let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
    let g:ale_echo_msg_error_str = 'E'
    let g:ale_echo_msg_warning_str = 'W'
    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

    nmap <silent> <Leader>ep <Plug>(ale_previous_wrap)
    nmap <silent> <Leader>en <Plug>(ale_next_wrap)

    nnoremap <silent> <Leader>ec :ALEToggle<CR>

    " troggle quickfix list
    function! ToggleErrors()
        let old_last_winnr = winnr('$')
        lclose
        if old_last_winnr == winnr('$')
            " Nothing was closed, open syntastic_error location panel
            lopen
        endif
    endfunction
    nnoremap <Leader>s :call ToggleErrors()<cr>

    let g:ale_set_highlights = 1
    highlight link ALEErrorSign  error
    highlight link ALEWarningSign Exception
endif

" }}}

```

**Comment by gatspy** [comment]
js比较大的文件也是卡顿啊。反而在macvim gui中一点都不卡顿。

**Comment by fengwang** [comment]
我的 vim 也是卡顿，在  iTerm2 中，后来在 .vimrc 最后边加了这三行好了：

`set re=1
set ttyfast
set lazyredraw`

**Comment by cuijianzhi** [comment]
> 我的 vim 也是卡顿，在 iTerm2 中，后来在 .vimrc 最后边加了这三行好了：
> 
> ```
> set re=1
> set ttyfast
> set lazyredraw
> ```

better than before
