### ISSUE TITLE
请问怎么清除安装呢

### ISSUE THREAD

**Issue by keeleys** [wklken/k-vim#236]

**Comment by wangaicc** [comment]
`sudo rm ~.vimrc .vim -rf`
#暴力删除吧

**Comment by wklken** [comment]
删根目录下.vim   .vimrc  .vimrx.bundles三个文件既可Sent from Mail Master
            On 06/08/2016 19:52, litai wong wrote:sudo rm ~.vimrc .vim -rf
#暴力删除吧

**Comment by LittleKey** [comment]
`cd ~ && rm -rf .vim .vimrc .vimrc.bundles && cd -`

**Comment by keeleys** [comment]
3
