### ISSUE TITLE
语法检查逻辑说找不到头文件

### ISSUE THREAD

**Issue by nofrish** [wklken/k-vim#238]
我想要用vim看Nginx的源代码，但是当打开一个文件时，总会显示Nginx的头文件找不到，各种数据类型不认识，如下所示：

```
>>  8 #include <ngx_config.h>
    9 #include <ngx_core.h>
   10 #include <ngx_http.h>
   11  
   12  
   13 typedef struct {
>> 14     in_addr_t         mask;                                                                                                                                                                           
>> 15     in_addr_t         addr;
>> 16     ngx_uint_t        deny;      /* unsigned  deny:1; */
   17 } ngx_http_access_rule_t;
```

刚开始以为是Syntastic的问题，把Syntastic卸载了，还是不行。后来猜测应该是YouCompleteMe的问题，Google了很久，不知道如何解决。

希望大家可以帮我看看，谢谢

**Comment by wklken** [comment]
试试前几个搜索结果, 应该跟ycm的conf文件相关

[youcompleteme c++ h file not found](https://www.google.co.jp/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=youcompleteme%20c%2B%2B%20h%20file%20not%20found)
