### ISSUE TITLE
提一个小建议

### ISSUE THREAD

**Issue by ttop5** [wklken/k-vim#241]
可以考虑一下没用的F1或者其他键设置成在左侧打开目录树的功能哈，类似于[https://github.com/ma6174/vim](https://github.com/ma6174/vim) ，挺方便的，希望考虑一下哈：）

**Comment by wklken** [comment]
`<leader>+n`, 即`,n`  开启nerdtree
F1目前禁用了系统帮助....但是绑了`dash` >_<

可以自行修改下vimrc中配置, 帮到nerdtree就行.
