### ISSUE TITLE
编译 YouCompleteMe 的时候出错。

### ISSUE THREAD

**Issue by insurgo222** [wklken/k-vim#242]
> git submodule update --init --recursive
error: no such remote ref 98712e7d0f6be2a090b6fda2a925f85e63656b58
Fetched in submodule path 'third_party/requests-futures', but it did not contain 98712e7d0f6be2a090b6fda2a925f85e63656b58. Direct fetching of that commit failed.

出现这个错误，不能继续编译YCM。不管是手动，还是自动都不行。

**Comment by wklken** [comment]
重新执行install.sh
原因是: ycm依赖很多第三方的包, install.sh过程中会去下载, 如果没下载完全就被中断进入下一步, 就会有问题.

或者可以看官方文档, 然后运行git命令, 下载完后再执行安装
