### ISSUE TITLE
archlinux安装不上YouCompleteMe

### ISSUE THREAD

**Issue by nerdneilsfield** [wklken/k-vim#243]
尝试在archlinux安装这个配置，但是YCM总是装不上，显示没有这个module.
用AUR安装也不行
尝试自己编译，依旧不能识别

**Comment by ttop5** [comment]
ubuntu上装了十多遍才装上，一直超时。。。

**Comment by wklken** [comment]
@ttop5 因为YCM有几百兆大小, 需要网速足够给力

**Comment by MrKiven** [comment]
手动装吧，会比较慢..

**Comment by nosiop** [comment]
@wklken 请问有什么办法，可以在安装的时候，不加载YCM。去掉这个功能安装，需要注释掉哪些文件，才能在安装阶段就禁用这个功能？感谢！

**Comment by wklken** [comment]
```
# vimrc.bundles line 43附近
Plug 'Valloric/YouCompleteMe'

# install.sh
step4的的代码块
```
