### ISSUE TITLE
进入 vim 后提示 YCM 不可用，因为导入 python 的 future 模块错误

### ISSUE THREAD

**Issue by m0ur3n** [wklken/k-vim#248]
进入 vim 之后，在下面会提示

> File "/Users/dongxu/Downloads/k-vim/bundle/YouCompleteMe/autoload/../python/ycm/base.py", line 22, in <module

回车时候，又显示了

> from future import standard_library

再回车

> ImportError: No module named future

再次回车 

> YouCompleteMe unavailable: No module named future

再次回车之后，错误信息消失

**Comment by Ma233** [comment]
在vim里试一下
```
:python print 'hello'
```

如果报错的话说明你的vim不支持python，可能需要重新安装一遍vim。

如果你使用的是brew，直接 `brew reinstall vim`即可。

**Comment by wklken** [comment]
@m0ur3n  应该是 @Ma233 提到的原因, 测试下

**Comment by uxgnod** [comment]
@Ma233 @wklken 抱歉，忘记回复了。 重新装了一下vim，问题解决了:smile:
