### ISSUE TITLE
python 3 最后的步骤安装不了，使用报错。

### ISSUE THREAD

**Issue by scottming** [wklken/k-vim#252]
安装时候提示我，安装 Cmake，
<img width="577" alt="2016-07-31 21 06 20" src="https://cloud.githubusercontent.com/assets/12830256/17276671/6ba41a48-5762-11e6-8d1f-eb5c13c40bc8.png">
我用 pip 找不到这个包，然后安了 Cmakepy，重试还是同样的提示。使用时会一直报错，
<img width="569" alt="2016-07-31 21 03 18" src="https://cloud.githubusercontent.com/assets/12830256/17276675/80b082a0-5762-11e6-8ebb-71a7898dde37.png">
请问我应该如何解决呢？

**Comment by wklken** [comment]
按照步骤, 安装cmake.

保证 `python install.py --clang-completer --system-libclang`可以执行成功

另外, 确认vim 支持python.

然后第二张图报错, 可以按照报错里面, 配置interpreter的路径到python2.6+ / 3.3+ 的地址

**Comment by scottming** [comment]
我已经添加 `export PYTHON_CONFIGURE_OPTS="--enable-framework"`到我的 ~/.zshrc 了，也运行过了。但还是报这个错：
```shell
➜  YouCompleteMe git:(master) python install.py --clang-completer --system-libclang
Searching Python 3.5 libraries...
ERROR: found static Python library (/Users/Scott/.pyenv/versions/3.5.2/lib/python3.5/config-3.5m/libpython3.5m.a) but a dynamic one is required. You must use a Python compiled with the --enable-framework flag. If using pyenv, you need to run the command:
  export PYTHON_CONFIGURE_OPTS="--enable-framework"
before installing a Python version.
Traceback (most recent call last):
  File "install.py", line 44, in <module>
    Main()
  File "install.py", line 33, in Main
    subprocess.check_call( [ python_binary, build_file ] + sys.argv[1:] )
  File "/Users/Scott/.pyenv/versions/3.5.2/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/Scott/.pyenv/versions/3.5.2/bin/python', '/Users/Scott/Documents/k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py', '--clang-completer', '--system-libclang']' returned non-zero exit status 1
```

**Comment by gatspy** [comment]
ycm 最新的安装不能使用--system-libclang

**Comment by scottming** [comment]
@gatspy 谢谢你，已经安装成功了，但我遇到一个新的问题，在写的时候补全时会报错这个：

```
a = np.<tab>
```
报错
```
HTTPConnectionPool(host='127.0.0.1', port=53033): Read timed out. (read timeout=
0.5)
```

**Comment by gatspy** [comment]
@scottming 我没用过numpy ，你可以参考下[numpy, timeout and YCM dying](https://github.com/Valloric/YouCompleteMe/issues/2192)

**Comment by gatspy** [comment]
我测试了下，在我的环境下是正常的。
我是用pyenv来管理多环境，用brew安装了python2.7.12。每次安装macvim和ycm的更新，我都会屏蔽pyenv环境，全部都是在brew安装的2.7.12中来操作。我贴下我安装macvim和ycm的操作步骤以便参考。
* 修改.zshrc注释掉pyenv相关设置
* brew uninstall --force python
* brew uninstall --force macvim
* brew rm --force macvim 
* brew install python
* cd /System/Library/Frameworks
* sudo mv Python.framework Python.framework.system
* sudo ln -s /usr/local/opt/python/Frameworks/Python.framework
* brew install macvim --override-system-vim
* cd /path/to/YouCompleteMe
* ./install.py --clang-completer 
`安装的时候编译错误 vim - YouCompleteMe Installation CalledProcessError`
`./install.py --clang-completer 因为新版本是ycmd需要libclang3.8`

.vimrc中就设置了一个ycm参数
let g:ycm_python_binary_path = '/usr/local/var/pyenv/versions/anaconda3-4.0.0/bin/python'

Note: 最痛苦的就是更新macvim或者更新ycm，我直接把macvim pin起来了。
```
YcmDebugInfo

Printing YouCompleteMe debug information...
-- Server has Clang support compiled in: True
-- Clang version: clang version 3.8.0 (tags/RELEASE_380/final)
-- Python completer debug information:
--   JediHTTP running at: http://127.0.0.1:51297
--   JediHTTP process ID: 58859
--   JediHTTP executable: /Volumes/Home/App/vim/k-vim/bundle/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/jedihttp.py
--   JediHTTP logfiles:
--     /var/folders/p_/t_0rr61x6b12qvz7w71n53vm0000gn/T/ycm_temp/jedihttp_51297_stdout.log
--     /var/folders/p_/t_0rr61x6b12qvz7w71n53vm0000gn/T/ycm_temp/jedihttp_51297_stderr.log
--   Python interpreter: /usr/local/var/pyenv/versions/anaconda3-4.0.0/bin/python
-- Server running at: http://127.0.0.1:51256
-- Server process ID: 58852
-- Server logfiles:
--   /var/folders/p_/t_0rr61x6b12qvz7w71n53vm0000gn/T/ycm_temp/server_51256_stdout.log
--   /var/folders/p_/t_0rr61x6b12qvz7w71n53vm0000gn/T/ycm_temp/server_51256_stderr.log
```

**Comment by scottming** [comment]
@gatspy 谢谢你的帮助，此问题已解决，另外我用 pyenv 没问题，需要加一行到 `~/.zshrc`

```
export PYTHON_CONFIGURE_OPTS="--enable-shared"  
```
然后重新下一个python的版本，切换到这个版本，安装必要包后重新安装 k-vim，就OK了。
另外那个 TIMEOUT 的毛病，需要

```
vim ./Documents/GitHubRepoes/k-vim/bundle/YouCompleteMe/python/ycm/client/completion_request.py
```
把 TIMEOUT 从 0.5 改成 2，参考在 [这里](https://github.com/Valloric/YouCompleteMe/issues/777#issuecomment-42033173)。

**Comment by chenjian158978** [comment]
@scottming @gatspy 谢谢你们的帮助

问下 @scottming 你的`~/.zshrc`中为何是

            export PYTHON_CONFIGURE_OPTS="--enable-shared"  

而不是
      
           export PYTHON_CONFIGURE_OPTS="--enable-framework"

我看了帖子，[You must use a python compiled with --enable-shared or --enable-framework (and thus a /usr/local/lib/libpython3.3m.dylib library #2057](https://github.com/Valloric/YouCompleteMe/issues/2057)

是后一种的

**Comment by yimeng** [comment]
env PYTHONCONFIGUREOPTS="–enable-framework" pyenv install 3.5.2
重新安装一下python环境

https://gist.github.com/sv99/b40b47413e01ce34f4d9

**Comment by floatval** [comment]
我按照楼上的安装方式试了下,搞不定.
最后自己在系统中下载了一个python3.5 然后制定ycm的补全引擎路径为/usr/bin/python3.5
就可以了

**Comment by 18309293349** [comment]
> 下载完Cmake了，但有新的错误。
> 我已经添加`export PYTHON_CONFIGURE_OPTS="--enable-framework"`到我的〜/ .zshrc 了，也运行过了。但还是报这个错
> 
> ```shell
> ➜YouCompleteMegit :( master）python install.py --clang-completer --system-libclang
> 搜索Python 3.5库...
> 错误：找到静态Python库（/Users/Scott/.pyenv/versions/3.5.2/lib/python3.5/config-3.5m/libpython3.5m.a），但需要动态库。您必须使用使用--enable-framework标志编译的Python。如果使用pyenv，则需要运行命令：
>   export PYTHON_CONFIGURE_OPTS = “ - enable -framework ”
> 在安装Python版本之前。
> Traceback（最近一次调用最后一次）：在< module > Main（）中的
>   文件“ install.py ”，第44行 
>     
>   文件“ install.py ”，33行，在主
>     subprocess.check_call（[python_binary，build_file] + sys.argv [1：]）在 check_call 中输入
>   文件“ /Users/Scott/.pyenv/versions/3.5.2/lib/python3.5/subprocess.py ”，第581行
>     引发CalledProcessError（retcode，cmd）
> subprocess.CalledProcessError：命令' [ ' /Users/Scott/.pyenv/versions/3.5.2/bin/python ' ' /Users/Scott/Documents/k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py '，'-- clang-completer '，' -  system-libclang ' ] '返回非零退出状态1
> ```

请问这个问题怎么解决的，我遇到相同的问题
