### ISSUE TITLE
请问支持变量名补全吗?

### ISSUE THREAD

**Issue by CosmoChan** [wklken/k-vim#254]
好像对已有变量名按 tab 不会补全, 用以前的 ctrl+N 也不补全了, 但是关键词等会补全, 请问应该如何设置呢
感谢你如此酷的工作!

**Comment by wklken** [comment]
tab被ultisnips占用, 用于代码片段扩展了, 肯定是不会出来的

变量名和关键字补全,  依靠的是ycm, 默认要敲击两个字母才能弹出补全下拉(可自定义), 然后通过`ctrl+jknp`选择即可

ycm还支持跳转到定义处的功能, 具体可以看其文档

**Comment by CosmoChan** [comment]
原来是之前YCM没编译好， Now it works, what a awesome job!
