### ISSUE TITLE
空格高亮可以去掉吗？

### ISSUE THREAD

**Issue by haolicheng** [wklken/k-vim#255]
如题！非常喜欢你的vim配置，可是我不想要空格高亮显示，能否去掉，注释里没有看到。

**Comment by wklken** [comment]
```
vimrc.bundles: line 60 附近

Plug 'bronson/vim-trailing-whitespace'
```

去掉这个插件好了

原先空格高亮展示, 然后`,+空格`一键去除所有空格(`<leader>+<space>`), 另外, 在vimrc中也有一个配置, 保存文件时自动删除这些空格.

总体还是非常有用的, 强迫症福音:)
