### ISSUE TITLE
python 无法正常使用quick run

### ISSUE THREAD

**Issue by CosmoChan** [wklken/k-vim#258]
你好, 我想请教一下quick run的原理是什么?我在vimrc文件中没有找到对应的语句
我之前使用quick run编译python是正常的, 昨天配置vim latex suite不知道改动了什么, 现在不管用quick run编译哪个测试过的python文件都会说module不存在, 我已经把用你的vimrc文件覆盖了我的, 问题依然存在
在vim中直接:!python %也是会有同样的错误
但是使用命令行运行python就不会有问题
不知道问题在哪...
我试过编译C++是很正常的

**Comment by wklken** [comment]
二分法, 把新增的配置注掉试试

另外, 换个新目录, 确认下是否是文件名和标准库名冲突了. quickrun配置在vimrc.bundles中的

**Comment by CosmoChan** [comment]
谢谢你, 找到了quickrun了
我发现不是我改了配置的原因, 是我之前都在shell中vim xxx.py, 这样的方式打开, 然后F10 quick run就没问题
今天没注意到自己是直接双击打开的py文件, 这样quick run就一直不行
请问你知道这是为什么吗

**Comment by wklken** [comment]
双击打开的是`macvim`?  可能`F10`被操作系统捕获了, 没有最终到达vim
