### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by vinsia** [wklken/k-vim#259]
Undefined symbols for architecture x86_64:
  "_clang_parseTranslationUnit2FullArgv", referenced from:
      YouCompleteMe::TranslationUnit::TranslationUnit(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<UnsavedFile, std::__1::allocator<UnsavedFile> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, void_) in TranslationUnit.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *_\* [/Users/vinsia/all-configs/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so] Error 1
make[2]: **\* [ycm/CMakeFiles/ycm_core.dir/all] Error 2
make[1]: **\* [ycm/CMakeFiles/ycm_core.dir/rule] Error 2
make: **\* [ycm_core] Error 2
Traceback (most recent call last):
  File "/Users/vinsia/all-configs/k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 371, in BuildYcmdLib
    subprocess.check_call( build_command )
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['cmake', '--build', '.', '--target', 'ycm_core', '--', '-j', '8']' returned non-zero exit status 2

ERROR: The build failed.

NOTE: It is _highly_ unlikely that this is a bug but rather
that this is a problem with the configuration of your system
or a missing dependency. Please carefully read CONTRIBUTING.md
and if you're sure that it is a bug, please raise an issue on the
issue tracker, including the entire output of this script
and the invocation line used to run it.

Traceback (most recent call last):
  File "install.py", line 44, in <module>
    Main()
  File "install.py", line 33, in Main
    subprocess.check_call( [ python_binary, build_file ] + sys.argv[1:] )
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/opt/python/bin/python2.7', u'/Users/vinsia/all-configs/k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py', '--clang-completer', '--system-libclang']' returned non-zero exit status 1
- echo 'Install Done!'
  Install Done!

好像是YCM插件安装不上，手动执行也不行

**Comment by wklken** [comment]
去掉`--system-libclang`, 重跑试试.....

**Comment by ajaxhe** [comment]
单独执行./install.py也报同样的错误
