### ISSUE TITLE
k-vim 面向的是程序员么？为什么默认的plug这么奇怪

### ISSUE THREAD

**Issue by yech1990** [wklken/k-vim#260]
像代码对齐，注释这样的功能为什么没有加进去？
是因为太多依赖了么？
https://github.com/Chiel92/vim-autoformat
https://github.com/tpope/vim-commentary

**Comment by wklken** [comment]
都有, 具体见对应插件官方文档.

```
Plug 'scrooloose/nerdcommenter'

" 快速赋值语句对齐
Plug 'junegunn/vim-easy-align
```

主要面向`python`和`golang`以及`c`系的程序员, `autoformat`暂时没有.
