### ISSUE TITLE
project plugin

### ISSUE THREAD

**Issue by DsonKing** [wklken/k-vim#261]
建议插件中集成项目管理插件

**Comment by wklken** [comment]
有哪些推荐的呢? @DsonKing

**Comment by DsonKing** [comment]
project 这个可以试一试
http://www.vim.org/scripts/script.php?script_id=69

**Comment by flniu** [comment]
楼上插件的github镜像：
https://github.com/vim-scripts/project.tar.gz

**Comment by wklken** [comment]
6年前的插件>_<# 总有一种老古董的感觉
当时应该也有测试过, 应该是看到多年都没更新的直接忽略了....

**Comment by wklken** [comment]
不加入, 需要的自行使用 `Plug` 集成
