### ISSUE TITLE
Mac vim 编辑 markdown 文件每次输入 ** 报错

### ISSUE THREAD

**Issue by scottming** [wklken/k-vim#265]
比如第 49 行
<img width="564" alt="screen shot 2016-10-07 at 8 01 23 pm" src="https://cloud.githubusercontent.com/assets/12830256/19189150/dc6c27f2-8cc8-11e6-8714-7868a984bd40.png">
只要输入星号就报错。有取消报错的办法吗？

**Comment by wklken** [comment]
YCM 没有正常安装导致的, 可以注掉youcompleteme, 或者根据文档重新编译安装试试
