### ISSUE TITLE
have plug vim-expand-region but error unknown function

### ISSUE THREAD

**Issue by pyclear** [wklken/k-vim#269]
Step3: update/install plugins using Vundle
- system_shell=/bin/zsh
- export SHELL=/bin/sh
- SHELL=/bin/sh
- true
- vim -u /Users/pyclear/.vimrc.bundles '+PlugInstall!' '+PlugClean!' +qall
  Error detected while processing /Users/pyclear/.vimrc.bundles:
  line  496:
  E117: Unknown function: expand_region#custom_text_objects
  Press ENTER or type command to continue

see .vimrc.bundles have plug vim-expand-region

**Comment by wklken** [comment]
`Vundle`在去年已经不用了, 最新版本用的`vim-Plug`,  更新到最新版本测试下

**Comment by pyclear** [comment]
我直接clone 的最新的master，看了看git log
  
    commit 10ee7cd769da8ceaec1b6691fb0df863547b828d
    Merge: f11e34a 7345545
    Author: wklken <wklken@gmail.com>
    Date:   Fri Sep 30 08:09:49 2016 +0800

是这个，所以是最新版本，但是到Mac下装还是像我提供的信息那样。我也很莫名其妙，看过相关资料知道用的是vim-Plug了。。

**Comment by wklken** [comment]
额, 应该是脚本没改>_<
你注解`vim-expand-region`重装试试

**Comment by pyclear** [comment]
我把那个函数注释后安装成功了，然后取消注释。使用的时候没报错。

**Comment by wklken** [comment]
额, 这个问题先保留开着, 我看下能否解决

**Comment by pyclear** [comment]
嗯，这个问题我其实自己的mac安装也遇到过,当时在解决mac Vim版本过低的问题所以这个问题被我忽略了。

**Comment by wklken** [comment]
```
    if exists("*expand_region#custom_text_objects")
        call expand_region#custom_text_objects({
        \ 'a]' :1,
        \ 'ab' :1,
        \ 'aB' :1,
        \ 'ii' :0,
        \ 'ai' :0,
        \ })
    endif
```
