### ISSUE TITLE
macOS 10.12 Ultisnips.vim error

### ISSUE THREAD

**Issue by awoooo** [wklken/k-vim#271]
![2016-10-30 10 06 53](https://cloud.githubusercontent.com/assets/8527864/19833995/dbbe00d8-9e88-11e6-80a3-2f8356690712.png)

**Comment by yaoshanliang** [comment]
Same error, how to solve that?

**Comment by wklken** [comment]
https://github.com/SirVer/ultisnips/issues/661
https://github.com/SirVer/ultisnips/issues/326
