### ISSUE TITLE
打开mvim闪退

### ISSUE THREAD

**Issue by Mod233** [wklken/k-vim#274]
这次更新了最新版后，一旦打开mvim就闪退啊
说的 
<img width="510" alt="screen shot 2016-11-04 at 6 19 54 pm" src="https://cloud.githubusercontent.com/assets/22654203/20006851/702755e0-a2d4-11e6-8249-193db1726b14.png">
跪求解答

**Comment by lipanXJ** [comment]
Try reinstall YouCompleteMe
![valloric youcompleteme a code completion engine for vim](https://cloud.githubusercontent.com/assets/15389690/20008114/3d857904-a2da-11e6-9034-816d98e856cb.png)

**Comment by wklken** [comment]
重编译`YCM`试试
