### ISSUE TITLE
Ubuntu14.04系统，安装时提示E117: 未定义的函数: expand_region#custom_text_objects

### ISSUE THREAD

**Issue by 1k2222** [wklken/k-vim#283]
Ubuntu14.04系统，安装时显示

> Step3: update/install plugins using Vim-plug
> + system_shell=/bin/bash
> + export SHELL=/bin/sh
> + true
> + vim -u /home/fomm/.vimrc.bundles +PlugInstall! +PlugClean! +qall
> 处理 /home/fomm/.vimrc.bundles 时发生错误:
> 第  515 行:
> E117: 未定义的函数: expand_region#custom_text_objects
> 请按 ENTER 或其它命令继续

按ENTER后一直卡死在以下界面不动
![2017-01-02 19 04 23](https://cloud.githubusercontent.com/assets/16257965/21588103/4d26b220-d11e-11e6-97b0-4b1547d0bf3d.png)

**Comment by wsdjeg** [comment]
因该是expand_region 脚本不再rtp里面，
