### ISSUE TITLE
macOS 10.12 为何打开左侧会出现这个东西

### ISSUE THREAD

**Issue by causlayer** [wklken/k-vim#284]
我想默认左侧的tab处于关闭状态，请问如何设置，
![18fcc782-d7fe-4fc0-9e9e-286694e6c2e5](https://cloud.githubusercontent.com/assets/7320355/21871599/1f89cece-d89e-11e6-904d-677bf6cc49b1.png)
谢谢

**Comment by epirus** [comment]
默认的不就是关闭的吗？

**Comment by shihuibei** [comment]
let g:nerdtree_tabs_open_on_gui_startup=0

**Comment by wklken** [comment]
默认是关闭的, `nerdtree_tabs`貌似有bug, 所以我注释掉了.
