### ISSUE TITLE
YCM 使用 Python 插件时 Python 意外退出

### ISSUE THREAD

**Issue by SeanWit** [wklken/k-vim#288]
执行完 PlugUpdate 然后重新编译 YCM 结果每次使用 vim 都报这个错误 是怎么回事 YCM 自动提示也失效了

vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 15 2017 06:00:55)
MacOS X (unix) version

**Comment by LittleKey** [comment]
都vim8了。。如果你不是很需要`跳转到代码定义处`这种功能的话不如换个配置简单的补全插件如何？

**Comment by HeroWit** [comment]
@LittleKey nvim-completion-manager ？
但还是想知道为什么插件升级后 YCM 失效并弹出 
![2017-03-16 5 49 00](https://cloud.githubusercontent.com/assets/3282728/24025936/9cb09cc0-0af8-11e7-9d2a-bc11bc21c881.png)

**Comment by wklken** [comment]
- ycm的报错.
- 最新版本验证, 提示/跳转定义等, 都正常
