### ISSUE TITLE
知乎专栏文章汇总

### ISSUE THREAD

**Issue by wklken** [wklken/k-vim#290]
开了个知乎专栏, 主要专注在后台开发/vim/python/效率/项目等等一系列内容

欢迎围观/评论/打赏:)

里面关于`vim`的文章, 会详细介绍`k-vim`中每一行配置的原因以及建议. 也方便大家优化自己的配置

这个issue临时当个索引用

- [wklken随想录: vim 杂谈 - 关于移动](https://zhuanlan.zhihu.com/p/25889426)
- [wklken随想录: vim 杂谈 - 关于快速编辑](https://zhuanlan.zhihu.com/p/25999103)

**Comment by wsdjeg** [comment]
不错，我也在研读你的项目源码哦，不过我做的是另外一个配置，就不晒链接了，我挺佩服这个项目的，服务器版本非常实用，无任何依赖。

**Comment by gatspy** [comment]
哈，开了专栏，要去关注了。。

**Comment by scorpioxiatian** [comment]
赞一个，学习了。。。
