### ISSUE TITLE
切换了iterm2，然后行、列高亮看不到了

### ISSUE THREAD

**Issue by ilaipi** [wklken/k-vim#292]
![image](https://cloud.githubusercontent.com/assets/1689135/24581455/5dbb37ac-174e-11e7-8e4f-491ec094d63f.png)

之前在mac自带终端里，鼠标当前行、列是高亮的
我看了下`.vimrc`，应该是
```bash
" 突出显示当前列
set cursorcolumn
" 突出显示当前行
set cursorline
```
这两行起的作用。
可能是换了iterm2之后背景色变成了黑色，跟高亮的颜色冲突了？
我搜了下怎么改高亮的背景色，说是
```bash
:hi CursorColumn guifg=NONE ctermfg=NONE guibg=#323232 ctermbg=236 gui=NONE cterm=NONE
```
但是我试了试没有用。应该怎么设置呢？

我的`nathanaelkane/vim-indent-guides`插件好像没有起作用

**Comment by ilaipi** [comment]
![image](https://cloud.githubusercontent.com/assets/1689135/24581534/e044b468-174f-11e7-8fb1-a762773149d3.png)

```
:highlight CursorLine ctermbg=LightBlue
```
这行在`nerdtree`插件里行高亮倒是可以用。换成
```
:highlight CursorColumn ctermbg=LightBlue
```
还是不能用。。

**Comment by wklken** [comment]
iterm2的关系, 不要改vim的配置

两个地方:
1. perferences - profile - terminal 选择utf-8 / 256color
2. perferences -  colors 变更终端相关颜色主题

**Comment by ilaipi** [comment]
@wklken 谢谢。
你说的是item2的菜单吧？
我看了下，第一点默认选的就是这样的。
第二点  没找到colors这个tab。
vim配置没有改了

**Comment by wklken** [comment]
![image](https://cloud.githubusercontent.com/assets/2002216/24690992/65f63a54-1a03-11e7-9717-ed001c7b32c3.png)

**Comment by ilaipi** [comment]
感谢！调整了一下 Background  然后就好了。这样看起来舒服多了。
