### ISSUE TITLE
YouCompleteMe补全方法异常

### ISSUE THREAD

**Issue by abcd1f2** [wklken/k-vim#293]
我用YouCompleteMe补全Python的时候，当我写os.op 会有提示 open函数，但是当我向下选中open函数时，os后面就变成op.en，就是我写的op字符被删掉了，选中后只有en了，这是什么情况

**Comment by wklken** [comment]
使用最新版本`k-vim`, 编译安装最新的`ycm`, 无法复现

如果有问题再打开
