### ISSUE TITLE
YouCompleteMe unavailable: No module named builtins

### ISSUE THREAD

**Issue by DogeCoding** [wklken/k-vim#294]
使用Vundle安装的插件，也不知道有没有安装完因为速度很慢我过了一会儿直接关掉shell，然后进入vim的时候提示 `YouCompleteMe unavailable: No module named builtins` YCM也不能用，这是什么错误啊咋解决

**Comment by wklken** [comment]
YCM很大, 在国内可能安装速度和成功率比较低
直接关掉shell, ycm肯定没有成功, 所以会报错

如果要用 YCM, 找个网络条件好点的地方, 重装
如果不用, 直接去掉ycm好了

**Comment by westfly** [comment]
这个感觉是没有到
bundle/YouCompleteMe 下执行 python install.py 脚本的问题，一般情况下需要重新链接库的。
