### ISSUE TITLE
plugupdate时出现以下错误

### ISSUE THREAD

**Issue by JerryAllison** [wklken/k-vim#298]
4 - Finishing ... Done!                                                |~
  5 x vim-ctrlspace:                                                     |~
  6     Invalid URI: https://git::@github.com/szw/vim-ctrlspace.git      |~
  7     Expected:    https://github.com/vim-ctrlspace/vim-ctrlspace.git  |~
  8     PlugClean required.                                              |~
~

**Comment by wklken** [comment]
```
:PlugClean
```

执行后

```
:PlugInstall
```

**Comment by wklken** [comment]
修正这行

- https://github.com/wklken/k-vim/blob/master/vimrc.bundles#L152

`Plug 'vim-ctrlspace/vim-ctrlspace'`

===========

已经patch, 稍晚更新
