### ISSUE TITLE
终端中用vim 打开文件 最大化的时候,状态栏会卡屏现象.这个怎么解决?

### ISSUE THREAD

**Issue by leeyongda** [wklken/k-vim#299]
终端中用vim 打开文件 点击终端窗口最大化的时候,状态栏会出现卡屏现象.
请问这个怎么解决?
如下图:
![2017-04-20 09-53-41](https://cloud.githubusercontent.com/assets/11832476/25209723/69c08038-25af-11e7-8cef-97d9bd3c451c.png)

**Comment by quentin-chen** [comment]
这个时候如果移动一下光标，airline 就应该能自动调整对了。

**Comment by wklken** [comment]
好像这个跟具体配置无关.....不可抵抗力>_<#
