### ISSUE TITLE
YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support

### ISSUE THREAD

**Issue by SeaflyDennis** [wklken/k-vim#301]
UltiSnips requires py >= 2.7 or py3
YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support
But my vim has support python:
![image](https://cloud.githubusercontent.com/assets/25523678/26043411/6ce35d3e-396f-11e7-903b-2ca56554001a.png)

**Comment by wklken** [comment]
@SeaflyDennis 
https://github.com/Valloric/YouCompleteMe/issues/1907

**Comment by onecer** [comment]
其实如果像我一样的Ubuntu系系统。apt-get install vim-nox就好了。不用重编译vim、

**Comment by GoodluckTian** [comment]
I have the same problem, and my link group vim is broken......help!!!!
![qq 20181213160213](https://user-images.githubusercontent.com/34158303/49924229-afcf3a80-fef0-11e8-84fb-979f51818d38.png)
![qq 20181213160227](https://user-images.githubusercontent.com/34158303/49924233-afcf3a80-fef0-11e8-8d9d-177843e665f8.png)
