### ISSUE TITLE
在iterm2和terminal下使用ycmd出现问题

### ISSUE THREAD

**Issue by tsungruihon** [wklken/k-vim#304]
当我在MacVim下使用ycmd是没有问题的，但当切换到iterm2或terminal下使用vim的时候会出现以下错误。`/k-vim/bundle/YouCompleteMe/autoload/../python/ycm/setu
p.py", line 37, in SetUpSystemPaths`

**Comment by wklken** [comment]
确认下`term`中使用`vim`的版本(和macvim不是一个版本的)

```
vim --version


```

确认下版本, 以及是否python support, 如果不是, 根据 ycm 文档, 重装或升级vim, 建议到8
