### ISSUE TITLE
wakatime不能正常工作

### ISSUE THREAD

**Issue by RanchoCooper** [wklken/k-vim#307]
[wakatime](https://wakatime.com/dashboard)一款记录coding time 的工具，虽然成功通过`Plug wakatime/vim-wakatime`安装插件，但无法正常工作。（插件在更换k-vim前正常工作）

**Comment by wklken** [comment]
k-vim 并没有对插件进行定制, 更多出现的情况是键位冲突.

----------

自行根据官方文档排查下吧, 确认配置/apikey/是否提交成功, 打开debug模式调试下
https://github.com/wakatime/vim-wakatime
