### ISSUE TITLE
启用ycm，插入模式下回车换行问题

### ISSUE THREAD

**Issue by gatspy** [wklken/k-vim#309]
问题表述: 启用ycm，新建一个带自动完成功能的文件类型，比如 vim a.py。只要出现`自动完成`提示框，方向键选择后，按回车`自动完成提示框`继续显示，导致回车不能换行。
macvim: 8.0 Included patches: 1-648
ycm: latest

是否有遇到这样问题的小伙伴呢？

**Comment by zhanglei541120** [comment]
+1

**Comment by wklken** [comment]
........好像一直以来都有这个问题, 只不过我一直用`ctrl+j/k`

我看看是不是ycm配置相关的问题

**Comment by wklken** [comment]
我发现为什么我不会发现这个问题, 因为补全时我从不敲`enter`

```
- ctrl + j/k 选择
- 如果后面是空格, 直接敲空格, 例如`def `, 空格触发
- 如果后面是其他字符, 直接敲字符好了, 直接触发, 例如调用函数时输入括号`hello(`
```

**Comment by wklken** [comment]
https://github.com/Valloric/YouCompleteMe/issues/232

**Comment by wklken** [comment]
更新到YCM最新版, 然后将如下配置加入`.vimrc.bundles`中`ycm`的配置

```
let g:ycm_key_list_stop_completion = ['<CR>']
```

**Comment by gatspy** [comment]
@wklken 谢谢~ 解决了。
