### ISSUE TITLE
自定义了一个syntax/python.vim

### ISSUE THREAD

**Issue by wklken** [wklken/k-vim#312]
最近在用pycharm看代码.....非常喜欢其默认主题

然而. 发现 vim 中默认一些东西没有高亮.

花了点时间处理了下, 借鉴了几个项目 https://github.com/wklken/python-syntax 

修改点:
1.  高亮 `self/cls`
2. 高亮所有operator
3. 高亮 类定义/函数定义的参数
4. 修改高亮 冒号/逗号/@/None

![image](https://user-images.githubusercontent.com/2002216/29246220-75719158-8025-11e7-9747-5b8bbf246f6b.png)

-------

同时, 如果要使用pyCharm的蓝色, 使用`monokai`主题后, 多加一行配置

```
Plug 'wklken/python-syntax'

let g:python_highlight_pycharm_monokai=1
```
![image](https://user-images.githubusercontent.com/2002216/29246228-8ea30e90-8025-11e7-91e7-866577da679f.png)

--------

比较遗憾的是, 目前函数调用是, 关键字参数无法高亮
另外, italic支持目前也没做, 仅调试成功了iterm2下comment的斜体

后面有机会再处理吧

**Comment by gatspy** [comment]
哈，喜欢gruvbox，喜欢gruvbox，喜欢gruvbox！！！
