### ISSUE TITLE
建议: 使用vim-choosewin套件

### ISSUE THREAD

**Issue by ejikuangren** [wklken/k-vim#320]
可以让nerdtree视窗快速切换，挺方便的

Plug 't9md/vim-choosewin' 
[t9md/vim-choosewin](https://github.com/t9md/vim-choosewin)
<br/>
配置
```
" Window Chooser ------------------------------
" mapping
nmap  -  <Plug>(choosewin)
" show big letters
let g:choosewin_overlay_enable = 1 
```

**Comment by wklken** [comment]
感谢建议, 但是 https://github.com/vim-ctrlspace/vim-ctrlspace 感觉更方便+强大
