### ISSUE TITLE
/ 搜索的问题

### ISSUE THREAD

**Issue by gatspy** [wklken/k-vim#321]
`/` 键按下去的时候，全部选中高亮？大家有遇到这样的问题吗？

vim版本
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2017 11:53:24)
macOS version
Included patches: 1-1272
Compiled by Homebrew
```

**Comment by wklken** [comment]
仅`/` 还是 `/ + 空格`?

**Comment by gatspy** [comment]
仅仅按`/` 就选择所有，但和`<leader>sa` 选择的方式又不同。

**Comment by wklken** [comment]
- 默认`\`会触发 `/\v` 进入搜索状态, 直接敲击空格才会全选
- 键位修改位置如图, `.vimrc`中

![image](https://user-images.githubusercontent.com/2002216/32639189-970d7e08-c5fd-11e7-8837-d9053e58b2f2.png)

- 如果还出现, 建议二分法排查

**Comment by petrewoo** [comment]
@gatspy 我也有相同的问题，不知道你是否解决。

**Comment by petrewoo** [comment]
@wklken 我这边仅仅按下/就会高亮所有，感觉应该不是/\v的问题，不知道关于高亮有什么设定会导致这样的问题？

**Comment by wklken** [comment]
没有额外的设置了，用二分法确认下吧，感觉可能是某个插件更新引入的

**Comment by petrewoo** [comment]
@wklken 这个是vim版本问题，vim应该已经修正。
详情见https://github.com/vim/vim/issues/2337

用brew安装vim的同学也许会遇到这样的问题（比如我），可以考虑如下解决方案：
1.把这个按键映射先注释掉，等待brew更新vim。
2.添加新的brew tap，更新vim的版本。
3.不使用brew，直接手动安装vim最新版本。

目前我使用方案1，正在研究方案2。
如果有其他的解决方案，也请大家@我，有新的进展我也会同步。

**Comment by wklken** [comment]
@petrewoo 感谢，我都是编译安装的，更新并不是那么及时>_<

**Comment by gatspy** [comment]
@petrewoo @wklken  `brew` 版 `macvim` 终于修复了这个问题。哈哈！！！

```bash
λ brew info macvim
macvim: stable 8.0-144 (bottled), HEAD
GUI for vim, made for macOS
https://github.com/macvim-dev/macvim
/usr/local/Cellar/macvim/8.0-144 (2,145 files, 34.2MB) *
```
