### ISSUE TITLE
from [module] import * 后，调用函数或变量时会有红色下划线提示

### ISSUE THREAD

**Issue by jetjog** [wklken/k-vim#323]
from [module] import * 后，下面直接调用该module里的函数或者变量时时会有红色下划线标出
虽然不影响运行，可是还是挺别扭的看起来，请问有没有办法去掉？谢谢

**Comment by wklken** [comment]
- 违反pep8规范了, 被插件检查出来了, 一般不建议这么用
- `syntastic_python_flake8_args` / `ale_python_flake8_args`
