### ISSUE TITLE
CPU占用过高

### ISSUE THREAD

**Issue by liuhao2050** [wklken/k-vim#324]
最近总是很卡，cpu占用也很高，不知道这个如何查询那个插件耗CPU

![image](https://user-images.githubusercontent.com/6995870/33321703-9a558f50-d481-11e7-90ad-a11ba93273b6.png)

**Comment by wklken** [comment]
1. 当出现vim占用很高, 开终端, `ps`查vim有多少个进程(可能某个窗口关闭未关vim导致)
2. 可以看下是什么操作导致的高占用 https://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow
3. 二分法, 停用一半插件, 缩小范围
