### ISSUE TITLE
python函数不能单独高亮

### ISSUE THREAD

**Issue by DisMeo** [wklken/k-vim#331]
函数高亮怎么设置
 list_a.append(n)
list_a的颜色和append的颜色是一样的，貌似不能单独设置

**Comment by wklken** [comment]
这个依赖于`python.vim`的语法插件

很遗憾目前没有比较好的方案实现函数高亮

我自己定义扩展了一个 https://github.com/wklken/k-vim/issues/312 可以参考下

-------------
