### ISSUE TITLE
YouCompleteMe unavailable: requires Vim 7.4.1578+.

### ISSUE THREAD

**Issue by lovezeropython** [wklken/k-vim#332]
☁  ~  vim 01.py
YouCompleteMe unavailable: requires Vim 7.4.1578+.
Press ENTER or type command to continue
这个问题怎么解决啊，能不能给python 加上自动补齐呢

**Comment by zxqchat** [comment]
@yk-Du 您好，我同样遇到这个问题，我升级了我的vim，但是它不能自动补全，我又重装了k-vim 但是依旧不能自动补全，检查了已经安装的插件YouCompleteMe 显示该插件已经安装，这是什么原因呢？

**Comment by yk-Du** [comment]
@zxqchat 
建议你可以先阅读相关插件的help，检查相关的环境。
我之前的回复是针对python库版本的，目前的vim（8.0以上）都支持+python属性但是又自身不带ptyhon库，需要你的机器自带。
由于目前可以下载到的vim都是32bit的，所以要求环境中使用32bit的python库，希望你可以检查这一点。
希望可以帮助你。

**Comment by wklken** [comment]
check YCM docs :)
