### ISSUE TITLE
如何设置python3 引用是自动提示python3 下面的包

### ISSUE THREAD

**Issue by lovezeropython** [wklken/k-vim#333]
如何设置python3 引用是自动提示python3 下面的包

**Comment by petrewoo** [comment]
@lovezeropython 你想问的问题是不是让YCM能在python3下生效？这样的话你只需要让YCM在python3的环境下编译就可以了

**Comment by wklken** [comment]
`let g:ycm_python_binary_path = 'python'` 将会自动使用项目的python解释器
