### ISSUE TITLE
能不能添加一个快捷键

### ISSUE THREAD

**Issue by ilaipi** [wklken/k-vim#335]
`nnoremap <silent> <leader>g :NERDTreeFind<cr>`

把这行加到`nerdtree nerdtreetabs`这个块下面。

作用是在当前打开的文件，按`<leader>g`，快速定位到`nerdtree`的这个文件那。

今天更新之后这个快捷键失效了，找了好久才找到，怕下次忘记。谢谢

**Comment by wklken** [comment]
多谢建议, 可以在自己的配置中维护哈
