### ISSUE TITLE
安装youcompleteme时路径出错

### ISSUE THREAD

**Issue by Flyour** [wklken/k-vim#338]
+ vim -u /root/.vimrc.bundles +PlugInstall! +PlugClean! +qall

子模组 'third_party/requests-futures'（https://github.com/ross/requests-futures）未对路径 'third_party/requests-futures' 注册
子模组 'third_party/ycmd'（https://github.com/Valloric/ycmd）未对路径 'third_party/ycmd' 注册
正克隆到 '/root/k-vim/bundle/YouCompleteMe/third_party/requests-futures'...
正克隆到 '/root/k-vim/bundle/YouCompleteMe/third_party/ycmd'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败
fatal: 无法克隆 'https://github.com/Valloric/ycmd' 到子模组路径 '/root/k-vim/bundle/YouCompleteMe/third_party/ycmd'
克隆 'third_party/ycmd' 失败。按计划重试
正克隆到 '/root/k-vim/bundle/YouCompleteMe/third_party/ycmd'...

**Comment by wangchaodong** [comment]
貌似python版本导致的,可以看YouCompleteMe项目的issues上的解决方法.
