### ISSUE TITLE
omnifunc returned bad value to YCM! Vim:E117:未定义的函数: pythoncomplete#Complete

### ISSUE THREAD

**Issue by pityhero233** [wklken/k-vim#340]
今天clone了一份k-vim，安装好dependencies后sh -x install，安装结束打开了一个python文件，发现ycm没有正常跳出。尝试按下Ctrl-Space，就出现了标题的错误。
我的ycm是咋了？

**Comment by jiangbai333** [comment]
> Ensure that your version of Vim is at least 7.4.1578 and that it has support for Python 2 or Python 3 scripting.
> [https://github.com/Valloric/YouCompleteMe#full-installation-guide](https://github.com/Valloric/YouCompleteMe#full-installation-guide)

`YouCompleteMe` 真的是非常难安。。。按照官方文档说的，看看你的vim版本以及是否支持python
