### ISSUE TITLE
进入VISUAL模式无法退出

### ISSUE THREAD

**Issue by liubozju** [wklken/k-vim#343]
![vim](https://user-images.githubusercontent.com/32894373/42987584-555f8488-8c2c-11e8-9f1d-c75c4b062747.png)
进入这种模式以后，按ESC无法返回normal模式，无法退出。

**Comment by the-eric-kwok** [comment]
![_deepin-terminal_20181204111235](https://user-images.githubusercontent.com/16463312/49416643-ab4ea780-f7b5-11e8-9e8b-47d242116c28.gif)
我这里可以
