### ISSUE TITLE
在普通用户下安装的，将root用户的.vimrc软连接到普通用户下的k-vim/vimrc，可以用，但是会报错

### ISSUE THREAD

**Issue by liubozju** [wklken/k-vim#344]
![22](https://user-images.githubusercontent.com/32894373/43560686-4746ccd4-9646-11e8-9740-be0932774fa5.png)
  报错信息：
 
vim addaccount.sh 
Error detected while processing /root/.vimrc:
line  660:
E185: Cannot find color scheme 'solarized'
Press ENTER or type command to continue

**Comment by wklken** [comment]
参考普通用户下软链, 有多个, 不只是vimrc
