### ISSUE TITLE
YouCompleteMe unavailable: object() takes no parameters

### ISSUE THREAD

**Issue by vuuihc** [wklken/k-vim#349]
- vim版本（building from source）
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  1 2018 18:09:26)
Included patches: 1-502
```
安装k-vim 然后在.vim/bundle/YouCompleteMe/ 下执行./install.sh --clang-completer 

vim打开文件会报题目中的错误

**Comment by wklken** [comment]
到YCM项目寻求帮助, k-vim 只是将其作为插件安装
