### ISSUE TITLE
mac os 下经常出现卡死状态

### ISSUE THREAD

**Issue by hidaen** [wklken/k-vim#351]
在 mac os 下经常出现卡死状况, 切换不到别到模式并且结束不了也保持不了, 各种快捷键不能用, 按 Esc 乱码, 最后只能是 close iterm2 窗口, 出现过很多次, 有遇到同样问题的童鞋吗, 在 issues 中没有看见, 两台 mac 都出现过很多次
如图所示我在输入状态就突然出现, 不能到任何别到模式下, 按ESC出现 "^[^[" 字符串, 最后只能是关闭这个终端
<img width="820" alt="screen shot 2018-12-10 at 11 23 41" src="https://user-images.githubusercontent.com/4091332/49709180-15f85b00-fc6e-11e8-8005-7998bd22ae84.png">

**Comment by Kira-cxy** [comment]
+1，我也偶尔会有同样的问题

**Comment by hidaen** [comment]
> +1，我也偶尔会有同样的问题

我这里是经常出现, 我都郁闷了, 写着写着就出问题, 然后代码还没保存, 我就哭了.
并且我随时可以复现这个问题，你也可以试试, 多拷贝粘贴一些内容进来, 基本上就出

**Comment by Kira-cxy** [comment]
> > +1，我也偶尔会有同样的问题
> 
> 我这里是经常出现, 我都郁闷了, 写着写着就出问题, 然后代码还没保存, 我就哭了.
> 并且我随时可以复现这个问题，你也可以试试, 多拷贝粘贴一些内容进来, 基本上就出

我倒是没有严重到影响编辑，请问要怎么复现？

**Comment by hidaen** [comment]
> > > +1，我也偶尔会有同样的问题
> > 
> > 
> > 我这里是经常出现, 我都郁闷了, 写着写着就出问题, 然后代码还没保存, 我就哭了.
> > 并且我随时可以复现这个问题，你也可以试试, 多拷贝粘贴一些内容进来, 基本上就出
> 
> 我倒是没有严重到影响编辑，请问要怎么复现？

多拷贝一些带符号的内容就会触发这个问题，比如这样 ->
<img width="1424" alt="screen shot 2018-12-10 at 16 18 07" src="https://user-images.githubusercontent.com/4091332/49719139-41437000-fc97-11e8-92ce-90c9dad97d20.png">

**Comment by wklken** [comment]
有可复现的步骤么?  @hidaen @Kira-cxy 


我目前mac os 10.14.1, iterm2 3.2.3, 没出现过这个问题

**Comment by hidaen** [comment]
> 有可复现的步骤么? @hidaen @Kira-cxy
> 
> 我目前mac os 10.14.1, iterm2 3.2.3, 没出现过这个问题

我这里是 mac os 10.14, iterm2 3.2.6，家里的 mac 也同样出问题，版本应该差别不大
我这里经常出现这个问题, 随时可以复现哈. 我忍这个很久了哈, 都差点换别都 IDE 了:D
基本上就是在编辑状态用粘贴板拷贝粘贴一些带符号的或则格式代码, 多粘贴几次就会出现这个问题,
我这里录制了一个视频不知道能不能看, 我上传一下
![vim-error-two](https://user-images.githubusercontent.com/4091332/49776710-1bba7300-fd38-11e8-8940-aab1856fb3e2.gif)

**Comment by hidaen** [comment]
> @hidaen 贴段文本给我吧

类似这样的,多一些符号的可能会更容易触发
nvim -u $HOME/.vimrc.bundles +PlugInstall! +PlugClean! +qall

**Comment by wklken** [comment]
尴尬, 复现不了.

两个思路你可以验证下:
1. 进入插入模式, 粘贴前, 先按F5, 然后粘贴, 看会不会出现一样的情况
2. `.vimrc.bundles` line 26附近, 所有插件的总开关, 二分法, 全部关掉, 每次开启一半, 验证, 可以找出是哪组插件导致的, 然后再到具体组找具体插件.  (如果全关掉还有, 那么意味着可能是基础插件, line36-line168 二分法)

```
let g:bundle_groups=['python', 'javascript', 'golang', 'shell', 'markdown', 'html', 'css', 'less', 'coffeescript', 'tmux', 'json', 'beta']
```

**Comment by hidaen** [comment]
> l', 'markdown', 'html', 'css', 'less', 'coffeescript', 'tmux', 'json', 'beta']

好的谢谢 wklken, 看来是我自己这里的问题, 我这里在查一下, 也许是我打开插件开太多了有冲突.
我先验证一下

**Comment by SlippyJimmy** [comment]
其实我也遇到这种情况，持续按Ctrl+C就能解决这种问题.
另外9.1版本三年了呀，期待坐着更新一波

**Comment by hidaen** [comment]
> 其实我也遇到这种情况，持续按Ctrl+C就能解决这种问题.
> 另外9.1版本三年了呀，期待坐着更新一波

你确定Ctrl+C就能解决这个问题？ 我用 wklken 说的二分法还没排除完呢, 下次再出现我试试, 除了这个问题基本上都是稳定的

**Comment by SlippyJimmy** [comment]
> > 其实我也遇到这种情况，持续按Ctrl+C就能解决这种问题.
> > 另外9.1版本三年了呀，期待坐着更新一波
> 
> 你确定Ctrl+C就能解决这个问题？ 我用 wklken 说的二分法还没排除完呢, 下次再出现我试试, 除了这个问题基本上都是稳定的

我用mac系统也卡死好多次了，卡死状态下按其它任何键都没有用，但是我连续按Ctrl+C时发现能重置vim输入状态，我个人是这么解决的

**Comment by wklken** [comment]
今年争取更新一波:)
刚好换工作三年>_<

**Comment by wklken** [comment]
Tencent......>_<

**Comment by hidaen** [comment]
> Tencent......>_<

👍 加个 v 呀... hidaen

**Comment by hidaen** [comment]
> > > 其实我也遇到这种情况，持续按Ctrl+C就能解决这种问题.
> > > 另外9.1版本三年了呀，期待坐着更新一波
> > 
> > 
> > 你确定Ctrl+C就能解决这个问题？ 我用 wklken 说的二分法还没排除完呢, 下次再出现我试试, 除了这个问题基本上都是稳定的
> 
> 我用mac系统也卡死好多次了，卡死状态下按其它任何键都没有用，但是我连续按Ctrl+C时发现能重置vim输入状态，我个人是这么解决的



> 其实我也遇到这种情况，持续按Ctrl+C就能解决这种问题.
> 另外9.1版本三年了呀，期待坐着更新一波

👍 🐂 啊，Ctrl + c 真的可以重置状态 🙏, 以前都是没保存难受, 早该提 issue 了

![screen shot 2019-01-18 at 12 15 31](https://user-images.githubusercontent.com/4091332/51365335-ca618880-1b1a-11e9-933d-f91f248c08a6.png)

**Comment by hidaen** [comment]
Ctrl + c 可以重制状态
