### ISSUE TITLE
为什么鼠标右键无法复制和粘贴

### ISSUE THREAD

**Issue by qingkong1998** [wklken/k-vim#352]
为什么鼠标右键无法复制和粘贴

**Comment by wklken** [comment]
![image](https://user-images.githubusercontent.com/2002216/50436226-cb3e3a80-091f-11e9-9745-253c99733c8a.png)

vimrc line 106, 启用鼠标

**Comment by qingkong1998** [comment]
我设置set mouse = a， windows下没有问题，Ubuntu18.04下有问题？

**Comment by qingkong1998** [comment]
![snipaste_2018-12-26_19-09-54](https://user-images.githubusercontent.com/13163880/50444299-a8714d80-0942-11e9-9192-91be22bbba2e.png)

**Comment by wklken** [comment]
复制粘贴不会是终端的默认行为吧>_<#

mac下iterm 默认支持

windows的cmd 应该也是

**Comment by qingkong1998** [comment]
Ubuntu18.04为什么就不行啊？
