### ISSUE TITLE
HTML文档emmet补全

### ISSUE THREAD

**Issue by SlippyJimmy** [wklken/k-vim#354]
请问wklen，您的emmet补全快捷键不是tab吧？在书写HTML文档时我按tab没法补全，改成什么了？
例如 `div.container>div.row` 按tab触发不了

**Comment by wklken** [comment]
https://github.com/mattn/emmet-vim#redefine-trigger-key

emmet默认是`<C-Y>`吧? 

默认tab目前YCM自动补全占用了

**Comment by SlippyJimmy** [comment]
官方文档上说明的是按`C-Y`后还要按`,`,但是按过`,`后无反应。难道是把`,`绑定为leader键的原因？
