### ISSUE TITLE
macos 10.14 (18A391)

### ISSUE THREAD

**Issue by hewenjerry** [wklken/k-vim#358]
使用vi和vim都报错 如下：
vim: Caught deadly signal SEGV

Error detected while processing function <SNR>173_PollServerReady[7]..<SNR>173_Pyeval:Vim: Finished.

line    4:
Exception MemoryError: MemoryError() in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored

**Comment by hewenjerry** [comment]
问题已经解决升级python 升级vim    google一下 说是版本太低了

**Comment by wklken** [comment]
YCM对vim有最低版本要求
