### ISSUE TITLE
mac下打开py文件提示错误

### ISSUE THREAD

**Issue by causlayer** [wklken/k-vim#360]
![47DDD709-E23A-4117-ADEC-AE13FE3177A7](https://user-images.githubusercontent.com/7320355/54869376-684f2900-4dd2-11e9-95a8-b8f3794db6a8.png)
![806C2177-37D2-42CA-BF2F-057240B10114](https://user-images.githubusercontent.com/7320355/54869378-6b4a1980-4dd2-11e9-9a0e-a1842c2a77fe.png)
![DEFEBF60-D96C-402C-8E27-5D9206738400](https://user-images.githubusercontent.com/7320355/54869397-a0ef0280-4dd2-11e9-942e-832515c337cb.png)

mac下打开py文件提示错误，首先是vim-isort的问题，另外是提示编码的问题。哪位遇到过同样的问题？
第一个问题因为本机安装的pylint需要isort，两个有冲突，我干掉了其中一个，第二个编码问题不知道如何解决

**Comment by wklken** [comment]
https://github.com/w0rp/ale/issues/966

根据报错及提示, 搜索对应插件的issues吧
