### ISSUE TITLE
关于配色问题，请教各位

### ISSUE THREAD

**Issue by Zhang21** [wklken/k-vim#361]
我使用默认的solarized主题，但是有一点我不习惯——**注释比代码还高亮**

我没有修改主题配置，但我不确定是我的问题还是默认如此。所以想请问一下大家也存在这种情况吗？

<br>

如果默认如此，大家有什么更好的配色方案分享吗？谢谢！

<br>

显示栗子:

![py](https://user-images.githubusercontent.com/18358275/55311917-d52f8680-5496-11e9-9d73-a9dabb4ef363.png)

![vimrc](https://user-images.githubusercontent.com/18358275/55311921-d660b380-5496-11e9-9264-5a8ebf1d90e7.png)

**Comment by wklken** [comment]
终端的配色要改下, 正常solarized dark配色就是官网展示的那个效果

https://ethanschoonover.com/solarized/

**Comment by Zhang21** [comment]
@wklken ，好的。

由于我使用的是CRT，它带有配色方案，可能是这个原因。
我先直接在linux机器上查看这个主题正常显示不，再判定CRT的问题。

**Comment by Zhang21** [comment]
经过验证，是我使用的CRT工具主题颜色的问题，在带有GUI的Linux里面正常显示。
更新至 `CRT v8.5` 后便自带了 solarized 主题。

因此，关闭此issue。
