### ISSUE TITLE
NEW: k-vim-vscode 键位设置

### ISSUE THREAD

**Issue by wklken** [wklken/k-vim#362]
https://github.com/wklken/k-vim-vscode

入坑vscode, 做了下配置, 尽量同k-vim一样的配置, 需要的可以参考

还在完善中:)

**Comment by gatspy** [comment]
已经同步了vsc中vim的配置了, 还在摸索中, 特别是vsc中想完全`键盘侠`有点困难吧?
特别是 sidebar中文件操作,  调试, 管理插件等还是直接用鼠标点方便点.
