### ISSUE TITLE
什么时候出个Idea的呢?

### ISSUE THREAD

**Issue by gatspy** [wklken/k-vim#365]
vsc的配置都出来了, 什么时候出个idea的呢?

**Comment by wklken** [comment]
idea的vim插件可配置程度略低, 很难达到vsc的水平, 例如sourround/multi-cursor/easymotion vsc的vim都原生支持了

**Comment by gatspy** [comment]
也是的. 可复用性还差, 总是用着用着就放弃掉了.😔,关了这个issue
