### ISSUE TITLE
报错 无法使用 请帮忙看一下

### ISSUE THREAD

**Issue by TaoRuan** [wklken/k-vim#367]
```
Vim: Caught deadly signal SEGV

Error detected while processing function <SNR>170_PollServerReady[7]..<SNR>170_Pyeval:Vim: Finished.

line    4:
Exception MemoryError: MemoryError() in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
[1]    53679 segmentation fault  vim
```

**Comment by caofengl** [comment]
同样的问题，mac 系统。
Error detected while processing function <SNR>165_PollServerReady[7]..<SNR>165_Pyeval:Vim: Finished.

**Comment by TaoRuan** [comment]
> 同样的问题，mac 系统。
> Error detected while processing function 165_PollServerReady[7]..165_Pyeval:Vim: Finished.

已解决 https://github.com/ycm-core/YouCompleteMe/issues/3165#issuecomment-507918641

**Comment by caofengl** [comment]
> > 同样的问题，mac 系统。
> > Error detected while processing function 165_PollServerReady[7]..165_Pyeval:Vim: Finished.
> 
> 已解决 [ycm-core/YouCompleteMe#3165 (comment)](https://github.com/ycm-core/YouCompleteMe/issues/3165#issuecomment-507918641)



> > 同样的问题，mac 系统。
> > Error detected while processing function 165_PollServerReady[7]..165_Pyeval:Vim: Finished.
> 
> 已解决 [ycm-core/YouCompleteMe#3165 (comment)](https://github.com/ycm-core/YouCompleteMe/issues/3165#issuecomment-507918641)

ok，多谢
