### ISSUE TITLE
如何修改 flake8 中最大行为 80 的设置？

### ISSUE THREAD

**Issue by yiran7324** [wklken/k-vim#369]
已经尝试方法：

```shell
" ~/.vimrc
autocmd FileType python setlocal colorcolumn=119
let g:syntastic_python_flake8_options='--ignore=F821,E302,E501'
```

**Comment by wklken** [comment]
如果是vim8, 自动启用的是`ale`; 不是 syntasitc

![image](https://user-images.githubusercontent.com/2002216/62338102-ce2e8880-b509-11e9-85c0-b40e2479322b.png)

**Comment by yiran7324** [comment]
![](https://i.loli.net/2019/08/02/5d43d4a77b5dd89862.png
)

我也是这个样子的，但是就是不起作用啊。

**Comment by Zhang21** [comment]
我也想问这个问题，我也想修改为120的长度。

**Comment by NullYing** [comment]
参考https://github.com/dense-analysis/ale/commit/191967cfeec78f3ba83d999462fe6e45e4f4c8de#diff-89fcb160c54b00efbfe4cde9e743ca22

```
g:ale_python_flake8_args setting to g:ale_python_flake8_options instead
```

**Comment by 0xKira** [comment]
`let g:ale_python_flake8_options = "--max-line-length=120"`
楼上正解，使用这一行即可

**Comment by Zhang21** [comment]
我都没有找到！想请问各位修改的是下面哪个文件？

```
vimrc
# OR
vimrc.bundles
# OR
bundle/ale/ale_linters/python/flake8.vim
```
