### ISSUE TITLE
鼠标复制黏贴，貌似会一直缩进

### ISSUE THREAD

**Issue by lddlww** [wklken/k-vim#374]
比如复制如下格式：
```
xx
  abc
  bbbxx

最后会变成：
xx
  abc 
     bbbxx
```
用鼠标复制黏贴，会一直缩进，请问这个怎么解决？

**Comment by akking** [comment]
`:set paste`
https://askubuntu.com/questions/256782/how-to-copy-paste-contents-in-the-vi-editor

**Comment by wklken** [comment]
k-vim配置的快捷键 F5

**Comment by lddlww** [comment]
@wklken 多谢多谢
