### ISSUE TITLE
请问怎么关闭语法检查啊，就是两个大于号 >> 

### ISSUE THREAD

**Issue by YJZyjz185672** [wklken/k-vim#380]
请问怎么关闭语法检查啊，就是两个大于号 >> ， 我把能想到的都注释了，还是会显示，奔溃
![image](https://user-images.githubusercontent.com/44958443/80908490-dc3c5e80-8d52-11ea-8a3b-26e994c158b1.png)

**Comment by YJZyjz185672** [comment]
又瞎注释了一通，解决了
vim .vimrc.bundles 

" syntastic
"if v:version < 800                                                                                                                   
"    Plug 'scrooloose/syntastic'
"else
"    Plug 'w0rp/ale'
"endif


vim .vimrc
" 插入模式下用绝对行号, 普通模式..."   除了此行和F2那一行，其他有行号相关的全部注释

**Comment by wklken** [comment]
syntastic及ale做的检查
