### ISSUE TITLE
airline显示不正常

### ISSUE THREAD

**Issue by boneylw** [wklken/k-vim#393]
各种办法都无解（版本v9.3）：

1. 安装powerline font
2. 修改iterm2 non-ASCII 字体为 powerline字体
3. 设置let g:airline_powerline_fonts = 1
4. #218 方式注释符号替换

<img width="356" alt="image" src="https://user-images.githubusercontent.com/2225484/146888805-b9813a6f-53d6-4fc1-bba9-f5791055cb1a.png">

**Comment by boneylw** [comment]
`Plug 'ryanoasis/vim-devicons` 这个插件导致的，注释掉就好了

**Comment by wklken** [comment]
`ryanoasis/vim-devicons` 用于优化展示文件树的icon, nerdtree左侧文件树, 可以开了看下不同文件类型是否正式正确

感觉应该是devicons没装成功?

-----
单独关闭

https://github.com/ryanoasis/vim-devicons/wiki/Extra-Configuration

```
" adding to vim-airline's tabline
let g:webdevicons_enable_airline_tabline = 1
" adding to vim-airline's statusline
let g:webdevicons_enable_airline_statusline = 1
```

**Comment by wklken** [comment]
https://github.com/ryanoasis/vim-devicons#installation

![image](https://user-images.githubusercontent.com/2002216/147031742-aef6ae7f-e61d-498e-ab45-4939a118a784.png)

**Comment by boneylw** [comment]
是的，安装nerd-font已经解决了，感谢
