### ISSUE TITLE
.ts文件应该如何配置

### ISSUE THREAD

**Issue by Zhang21** [wklken/k-vim#395]
`.ts`文件目前好像识别不了，这个应该如何配置呢？

**Comment by wklken** [comment]
默认没有支持ts.

------

google: vim typescript plugin

需要类似这样的插件: https://github.com/leafgarland/typescript-vim

**Comment by Zhang21** [comment]
谢谢作者，已解决。

步骤如下:

```
# 克隆git仓库
git clone https://github.com/leafgarland/typescript-vim.git ~/.vim/bundle/typescript-vim

# 修改vim-plug，添加插件
Plug 'leafgarland/typescript-vim'

# vim里操作下PlugStatus或PlugInstall生效
```

**Comment by wklken** [comment]
`Plug 'leafgarland/typescript-vim'` 加一句之后执行PlugInstalll就行, 不需要clone
