### ISSUE TITLE
使用ag作为CrtlP的搜索引擎

### ISSUE THREAD

**Issue by dd1994** [wklken/k-vim#44]
ag速度暴快
参考：https://github.com/thoughtbot/dotfiles/blob/master/vimrc
https://github.com/ggreer/the_silver_searcher
```VIML
" Use The Silver Searcher https://github.com/ggreer/the_silver_searcher
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif
```
我觉得这是个非常好的设置，不搜索.gitignore里面忽略的文件，不用缓存。
我就不提pull requests了哈

**Comment by kdurant** [comment]
@dd1994 @wklken 
```VimL
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
```
会输出```ERR: pcre_compile failed at position 8. Error: PCRE does not support /L, /l, /Nname, /U, or /u```

我是windows系统，用的是编译好的ag.exe

**Comment by wklken** [comment]
`ag`用了一段(centos/mac, 不用win好久了......), 现在转到使用`dyng/ctrlsf.vim`, 这个用起来更像sublimetext的全局搜索

你这个可以执行ag.exe查看当前安装版本支持的参数

---------------

目前ag未加入的原因是, 要单独安装ag, 虽然可以通过检测决定是否使用, 但是例如`ag.vim`, 和`dyng/ctrlsf.vim` 这类好用的插件, 不好设为默认

**Comment by wklken** [comment]
我现在一直在用, 配合Bundle "dyng/ctrlsf.vim" 很赞
只是因为涉及到安装ag, 还在犹豫要不要配置进来

**Comment by dd1994** [comment]
其实本来就有很多依赖了，比如那个 YCM 依赖那么多，其实再加个依赖也无所谓，而且 ag 安装也很方便...
