### ISSUE TITLE
YouCompleteMe无法自动补全python模块和方法

### ISSUE THREAD

**Issue by vincentor** [wklken/k-vim#5]
我发现我的YCM没法自动补全python模块和方法，是还有什么配置要改么？我google了很久没找到对应的解决办法，只能请教你了，谢谢。具体的情况如下：http://ascii.io/a/3938, 可以看到当我输入<code>import os.</code>的时候，并不会弹出os下所包括的模块。我看到网上有人说需要在vimrc设置

<pre>let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/cpp/ycm/.ycm_extra_conf.py'
</pre>

但我没有看到你的vimrc中有设置。我自己加上去了也没有起作用。

**Comment by wednesdaysunny** [comment]
let g:ycm_global_ycm_extra_conf="~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"
let g:ycm_key_invoke_completion=''

这样配置了 貌似不行啊 求解

**Comment by wangyeming** [comment]
sorry，冒昧的问一个问题，我的mac系统，用vim-bundle安装的
youcompleteme插件, 在python中几乎没有任何提示，只会提示该文件中已经输入的单词，我google了好久都没看到解答，大大能不能帮我解答一下啊！

**Comment by mitu626** [comment]
@wangyeming 你编译的时候没有提供语义支持吧？

**Comment by bestshiyuhua** [comment]
@wangyeming 我现在也是这样，你解决了吗

**Comment by ketor** [comment]
@bestshiyuhua 安装YCM的官方教程编译一遍吧

**Comment by wangyeming** [comment]
@bestshiyuhua 还没解决

**Comment by jiangyantao** [comment]
@wangyeming @bestshiyuhua 
我也遇到这个问题了，然后我是通过在.vimrc 里的Plugin 'Valloric/YouCompleteMe'下面加上以下4句解决的：
let g:ycm_seed_identifiers_with_syntax=1
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_min_num_of_chars_for_completion=2
let g:ycm_path_to_python_interpreter='/usr/local/bin/python3'
