### ISSUE TITLE
待处理问题: '#'操作细节

### ISSUE THREAD

**Issue by wklken** [wklken/k-vim#57]
1.
`#`号查找时第一个不往下走, 其实我大多数时候只想看下光标下变量在哪些位置出现而已, 不需要跳到下一个, 第一次不跳, 按n/N再开始跳.....目测要写脚本实现

2.
'#'在写注释的时候, 默认是忽略排版的, 每次都跳到行首, 苦逼地排版移动到合适的位置
或者干脆先写注释完再加'#', 需要看下能不能解决这个问题

**Comment by czzshr** [comment]
非常同意！
今天学CSS的时候，用"#"也遇到了这个问题，每次一按”#“，缩进直接就失效了，光标跑到行首去了。。

**Comment by LittleKey** [comment]
我一直把这当Feature....原来是Bug麽....

**Comment by wklken** [comment]
已处理, 可以拉新的 vimrc测试下

[sof链接](http://stackoverflow.com/questions/2360249/vim-automatically-removes-indentation-on-python-comments)

增加的代码

```
" for # indent, #号注释不切回行首		 
 autocmd BufRead *.py inoremap # X<c-h>#
```

注意, 这里只处理py文件, 其他类型按需自行添加吧
可以测试下, 有问题再反馈哈:)
