### ISSUE TITLE
Mac下unicode error

### ISSUE THREAD

**Issue by suemi994** [wklken/k-vim#78]
对于Mac下地vim，安装k-vim后，输入'/'字符后再在改行输入任何字符都会报unicode error错误。
不知道有木有解决的办法？

**Comment by wklken** [comment]
很抱歉没解决你的问题....
近期ycm更新蛮多的, 可以尝试重装下>_<#

**Comment by LittleKey** [comment]
我这没有问题，重现不能。。。

我也是mac，系统版本是10.10
vim版本是7.4 MacOS X (unix) version
