### ISSUE TITLE
Python 新行注释会自动顶到行首

### ISSUE THREAD

**Issue by Damnever** [wklken/k-vim#82]
如:

```
while 1:
# 这里自动跑到行首，有点蛋疼

while 1:
    print 'Hi!'
    # 想让它保持格式，怎么做？
```

**Comment by wklken** [comment]
这个和indent有关系, 我这边也这样

暂时没空调试, 有木有谁有解决方案?

**Comment by wklken** [comment]
已处理, 可以拉新的 vimrc测试下

[sof链接](http://stackoverflow.com/questions/2360249/vim-automatically-removes-indentation-on-python-comments)

增加的代码

```
" for # indent, #号注释不切回行首		 
 autocmd BufRead *.py inoremap # X<c-h>#
```

**Comment by LittleKey** [comment]
我这还是会回首行
文件名 `test.py`

**Comment by wklken** [comment]
@LittleKey 
你照我贴的帖子处理方式手工走一遍试试
我这边测试没问题

**Comment by LittleKey** [comment]
@wklken 我直接在vim里设置`inoremap # X<c-h>#` 这样是可以工作的，估计是因为我这有什么改动和你的冲突了, 我之后慢慢看好了

**Comment by LittleKey** [comment]
@wklken 我打开已存在文件的话是会生效的， 不过如果是新建py文件(`e.g: vim test.py`)的话就不工作

添加一行 `autocmd BufNewFile *.py inoremap # X<c-h>#` 可以解决。。（感觉应该有能写成一行的方法，懒得去查了。。。

**Comment by wklken** [comment]
@LittleKey 
加个逗号就能一行
```
" for # indent, python文件中输入新行时#号注释不切回行首
autocmd BufNewFile,BufRead *.py inoremap # X<c-h>#
```

已经更新到github了

**Comment by spacewander** [comment]
这个问题似乎还有更好的解法。
参考stackoverflow上的两个问题：
http://stackoverflow.com/questions/354097/how-to-configure-vim-to-not-put-comments-at-the-beginning-of-lines-while-editing
http://stackoverflow.com/questions/2063175/vim-insert-mode-comments-go-to-start-of-line

用`cindent`替换掉`smartindent`可解。

目前我是用`cindent`替换掉`smartindent`和`autoindent`，暂时还没发现有问题。

**Comment by LittleKey** [comment]
@spacewander cool!
