### ISSUE TITLE
300 多行的 Python 代码，vim 光标移动奇卡无比

### ISSUE THREAD

**Issue by longgeek** [wklken/k-vim#83]

**Comment by longgeek** [comment]
测试发现：

    set cursorcolumn

设置上面选项左右移动会变慢，去掉就和 bash 里移动光标速度正常了。
但是发现设置不设置这个选项都没有变化。

**Comment by wklken** [comment]
hi, 我这边测试过千行级别的代码, 多开buffer/tag, 移动,输入,自动补全和跳转等都正常

第一个方式: 使用二分法进行一半一半注解, 然后打开文件看下 (建议)

第二个方法, 如果方便的话, 将代码贴出来测试下

**Comment by caimaoy** [comment]
个人猜测和300行没有关系，应该是某个要解析python的插件，进到了一个很深的树里面去了 - -|||

**Comment by wklken** [comment]
同时对代码和插件进行二分吧

**Comment by longgeek** [comment]
上下移动问题找到了，是相对行号在作怪。。。。

**Comment by longgeek** [comment]
代码: https://dpaste.de/1QXd

**Comment by wklken** [comment]
Sorry, 可能只是你的机器上有问题
我这边拉你的代码上下左右, 跳转, 补全等一切正常, 没有出现你描述的现象

无法复现, 建议处理方式
1. 二分法排查是否是哪个插件的问题(or去掉k-vim配置确认下直接打开是否有问题)
2. 重装一把vim/k-vim (最后的办法)

**Comment by taizilongxu** [comment]
vim --startuptime timefile the_file_you_want_to_edit 

查看timefile 看看延迟在哪里
