### ISSUE TITLE
vim 编辑 Python 文件，出现语法错误或者代码规范提示的背景色如何设置？

### ISSUE THREAD

**Issue by longgeek** [wklken/k-vim#84]

**Comment by longgeek** [comment]
像图片中的 import 背景色，如何改呢？试过 mac 终端的偏好设置里颜色设置不管用，怀疑是语法检测插件的原因。
![674d2b40-b8c4-41a9-94bb-95b1584e382a](https://cloud.githubusercontent.com/assets/2102615/5664413/4965fe3a-978b-11e4-8cba-db96ea0f9897.png)

**Comment by spacewander** [comment]
像`highlight SyntasticWarningSign guifg=white guibg=black`这样就能设置Warning的前景色和背景色。

具体内容，可以用`:help syntastic-error-signs`查看相关文档。

**Comment by longgeek** [comment]
不起作用
