### ISSUE TITLE
如何设置 vim 代码自动补全提示框的背景色和透明度

### ISSUE THREAD

**Issue by longgeek** [wklken/k-vim#85]
下图中的自动补全提示信息会经常挡着下面的代码，想换个颜色并设置一定透明度，如何设置呢？

![a471d529-55e2-46f8-950c-618a166c014e](https://cloud.githubusercontent.com/assets/2102615/5665337/bea892be-9792-11e4-9a4c-efdce8e32dc2.png)

**Comment by spacewander** [comment]
同样的，设置下面的语法高亮组：
```vimscript
highlight Pmenu     guifg=xx guibg=yy       "normal item
highlight PmenuSel    ...    "selected item
highlight PmenuSbar   ...    "scrollbar
highlight PmenuThumb  ...    "thumb of the scrollbar
```

Vim的高亮只支持使用特定的颜色或者#012345这样的rgb值，所以设置不了透明度。

**Comment by longgeek** [comment]
@spacewander 多谢。
