### ISSUE TITLE
install.sh 在安装YouCompleteMe时的一个bug？

### ISSUE THREAD

**Issue by spacewander** [wklken/k-vim#86]
最近在给Debian安装YouCompleteMe的时候遇到的一个问题，即在安装了clang之后，虽然`which clang`返回真，但是在安装的过程中，会由于找不到`/usr/lib/libclang.so`而失败。

看了下，`which clang`返回的是`/usr/bin/clang`，而不是`/usr/lib/libclang.so`。那么就有可能出现这种情况：即使安装了二进制文件clang，却没有安装链接库libclang.so。

所以install.sh中，判断libclang是否存在的语句，也许得改成`-f /usr/lib/libclang.so`？

**Comment by wklken** [comment]
`which`命令, 在PATH中查找命令, 主要判定是否装了, 至于链接库, 根据系统不同或者编译安装选项不同, 路径不一定是 `/usr/lib/libclang.so`

**Comment by fangwentong** [comment]
@spacewander Ubuntu 14.04 也会出现找不到libclang.so的情况， 原因是缺少符号连接

 wklken/k-vim#77 提到过, 可以手动`locate libclang.so`， 查找`libclang.so.x`这种名称的文件， 然后添加一个符号链接应该就可以了.

**Comment by spacewander** [comment]
@fangwentong 嗯，这个问题我已经手工解决了。谢谢你的建议。
