### ISSUE TITLE
Solarized 主题颜色问题

### ISSUE THREAD

**Issue by AndsonYe** [wklken/k-vim#88]
![screenshot from 2015-02-15 16 38 08](https://cloud.githubusercontent.com/assets/8774500/6202636/a1a98170-b531-11e4-9f98-8b708234d3c1.png)
我的安装好后使用solarized底部状态栏颜色太晃眼，请问如何设置？
另外
![screenshot from 2015-02-15 16 38 34](https://cloud.githubusercontent.com/assets/8774500/6202639/c52c8228-b531-11e4-8bfd-d2b95dd696e8.png)
使用solarized主题的时候YouCompleteMe的选中部分颜色也很难看清，在.vimrc中添加highlight PmenuSel guifg=#009999 也没有什么变化，请问具体是怎么设置额？

**Comment by wklken** [comment]
monokai主题应该是正常的 

----------------------
solarized, 装完貌似都是这样子很丑, 要改terminal的颜色
[link](https://github.com/altercation/vim-colors-solarized#important-note-for-terminal-users)

试下是否能行? ps:你用的神马系统?
我目前用mac - iterm2 , iterm改换颜色就正常了

**Comment by AndsonYe** [comment]
Ubuntu 12.04.
设置let g:solarized_termcolors=256之后不会晃眼了 不过还是比较难看，应该加粗的字也没有加粗。
貌似用ubuntu的gnome-terminal都会有这个问题
