### ISSUE TITLE
安装了之后好像不能输入中文了。。

### ISSUE THREAD

**Issue by yanwen** [wklken/k-vim#92]
输入法是 系统自带的拼音输入法
系统是 10.9.5

**Comment by wklken** [comment]
......

我是从10.8一路升上来的, 目前10.10.3, 没发现这个问题, 但是之前google有人提到, 具体解决方案google下吧

**Comment by yanwen** [comment]
呃。。其实 我是Google了好久未果之后才发帖求问的。。

具体现状是：输入拼音的时候 直接就变成了英文了。 拼音打出来的字也不能选择。

**Comment by yanwen** [comment]
找到了这个方法。。。我试试先。。看行不行。。

https://github.com/wklken/k-vim/issues/4

**Comment by wklken** [comment]
#4 , 确认下是否解决, 问题先关闭

**Comment by Leeiio** [comment]
应该是和什么插件冲突了，因为不用k-vim配置是可以正常输入中文的
