### ISSUE TITLE
Vim退出后，文件内容驻留在命令行界面,类似tail

### ISSUE THREAD

**Issue by shnode** [wklken/k-vim#93]
![image](https://cloud.githubusercontent.com/assets/7784713/6525120/793bd2e6-c43c-11e4-8dd2-b9034fe3976f.png)

这样导致退出后，之前的cli命令都被掩盖了。

查看的时候也类似head。

请问怎么设置。

**Comment by LittleKey** [comment]
[改这里](https://github.com/wklken/k-vim/blob/master/vimrc#L90)

**Comment by wklken** [comment]
k-vim文档中有写, vimrc里面也有注释



Sent from Mail Master
On 03/06/2015 20:21, LittleKey wrote:

改这里

**Comment by shnode** [comment]
我的vimrc 里面并没有这句啊，另外发现nano也是这样的，怀疑是命令行的问题

**Comment by wklken** [comment]
.....
k-vim的vimrc从第一版本开始就有这句, 个人习惯问题, 所以我在文档标注了可以注解
仔细找下, 加个引号注掉了就好了

```
set t_ti= t_te=
```
