### ISSUE TITLE
扩展语言包插件

### ISSUE THREAD

**Issue by dd1994** [wklken/k-vim#94]
vim 比较保守，很多新出的语言比如 Elixir，CoffeeScript 没有默认支持（在我的 vim 7.4)下，这个 扩展
https://github.com/sheerun/vim-polyglot 收集了几乎所有的语言包插件，比如它的 Ruby 就用的 [vim-ruby](https://github.com/vim-ruby/vim-ruby), Elixir 用的是 [vim-elixir](https://github.com/elixir-lang/vim-elixir)，几乎都是公认的的最好的语言插件。Give it a try!

**Comment by wklken** [comment]
ok, 我会试用一段时间, thx:)

**Comment by wklken** [comment]
暂时不会再最近版本加入
虽然这个插件很强大, 有些违背按需配置的原则, 考虑ing, 继续试用,
