### ISSUE TITLE
tomorrow 主题

### ISSUE THREAD

**Issue by dd1994** [wklken/k-vim#95]
solarized 和 molokai 真是有点过于经典了，同学们都有点腻歪了。
[Tomorrow](https://github.com/chriskempson/tomorrow-theme) 非常柔和，看起来非常舒服，而且提供 dark 和 light 可选，都有 7000 多 star 了，可以通过 `ChrisKempson/Vim-Tomorrow-Theme` 用 vundle 安装

**Comment by Menghongli** [comment]
nice one

**Comment by IIMare** [comment]
请问怎么使用呢。在.vimrc中怎么设置呢？

JIANG Di <notifications@github.com>于2015年3月12日星期四写道：

**Comment by dd1994** [comment]
咦我关了你怎么还能看到。

用 vundle 安装啊 `Plugin 'chriskempson/vim-tomorrow-theme'` 然后`:PluginInstall` 就好了。
然后在 vimrc 里面加上 `colorscheme Tomorrow-Night`

**Comment by IIMare** [comment]
已经弄好了，谢谢：）

JIANG Di <notifications@github.com>于2015年3月14日星期六写道：

**Comment by wklken** [comment]
已加入, 待发布
