### ISSUE TITLE
不知该如何设置代码提示默认选中第一个，然后按tab键直接上屏？

### ISSUE THREAD

**Issue by rogerdehe** [wklken/k-vim#99]
长期使用idea，k-vim的代码提示与idea很大的不同就是代码提示并不是用tab键上屏的，而是使用上下键选择，因为上下键离手较远，不如tab键来的近，总觉得不习惯

**Comment by caimaoy** [comment]
我没太注意看配置，我用YCM 用的是tab， 你试试<c-n>和<c-p>

**Comment by wklken** [comment]
ctrl + n/p
ctlr + j/p
上下方向键


至于tab, 留给了 'SirVer/ultisnips' /  'honza/vim-snippets'

=================
自动补全 以及 代码片段, 两大神器, tab很难兼得
需要的话看下配置, 自行修改试试

**Comment by rogerdehe** [comment]
谢谢，一直不知道可以使用ctrl + n和ctrl + j，还是很方便的

在 2015年4月3日 下午6:45，wklken <notifications@github.com>写道：
